### ISSUE TITLE
[0.2 XMR] Consider merging refund and cancel command into one

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#1020]
There is not really a reason for the end user to disguise between the two. They must always be executed together anyway.

**Comment by binarybaron** [comment]
We use bounties to incentivize development and reward contributors. All issues available for a bounty have the `Bounty 💰 ` label.

To receive the bounty of this issue, you agree to these conditions:

- Your changes must follow the [styling guidelines](https://github.com/comit-network/xmr-btc-swap/blob/master/CONTRIBUTING.md).
- Bounties will be set and awarded at discretion of @binarybaron .
The issues eligible for a bounty are labelled 'Bounty 💰' and have the amount of the bounty specified in the title in this form: [1 XMR].
- An issue is considered resolved when the patch(es) proposed by the contributor is/are merged in the appropriate repository according to terms of the issue.
- The first person who resolves an issue in its entirety will receive the entire amount of the bounty.
- If the issue is resolved collaboratively by more than one person, the reward will be distributed among the contributors
- Let the Maintainers know if you intend to work on a bounty, so that the issue can be assigned to you. Being assigned to an issue doesn't make that issue resolvable only by the assignee. It's meant to avoid duplication of efforts and not to discourage collective works.
- After the issue is resolved, contact @binarybaron and claim your bounty (remember to provide them with a Monero address).

**Comment by delta1** [comment]
Hey I’ll pick this up this week

**Comment by binarybaron** [comment]
Awesome!

**Comment by binarybaron** [comment]
@delta1 do you have a xmr address for me?

**Comment by delta1** [comment]
Sent to you on Matrix. Thanks @binarybaron

**Comment by binarybaron** [comment]
Bounty has been paid out!
