### ISSUE TITLE
ASB v0.10.1 Not re-registering with Rendezvous node

### ISSUE THREAD

**Issue by SIEVEofEratosthenes** [comit-network/xmr-btc-swap#1055]
**Describe the bug**
We run a rendezvous node, and while in our logs wee see that we have a few users adding their ASB to our rendezvous, after a few hours the node expires and never renews. With rendezvous v0.1.0, we noticed a re-registering of the nodes after expiry. Not sure if this is with ASB or rendezvous v0.2.0, so I'm posting here

As such, after a few hours a `list-sellers --rendezvous-point ...` returns no Market Makers. 

**Lost/trapped Funds**
No

**Debug logs**
I've obscured the actual nodes connecting except the last one which is mine as a test. 

```shell
$ sudo journalctl -f -u rendezvous
-- Logs begin at Mon 2022-05-30 07:06:08 UTC. --
Jul 21 22:57:09 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-21 22:57:09  INFO Peer registered peer=xxxxxxxxxxxx namespace=xmr-btc-swap-mainnet addresses=["/dns4/------------------/tcp/9942/p2p/xxxxxxxxxxxx"] ttl=7200
Jul 21 22:57:43 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-21 22:57:43  INFO Peer registered peer=klNBAFX8ns1hsUdiBRhn7EMjxv609Y0HZOdmpS3iUcNRcbS/jmFdAQMRMckoBvD0 namespace=xmr-btc-swap-mainnet addresses=["/onion3/xxxxxxxxxxxx:9941"] ttl=7200
Jul 21 23:00:09 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-21 23:00:09  INFO Peer registered peer=3cSuqmlD1vLey+SjrvGNSghdndGbgWrCV3CiPr3U98v3H1qF2wGU4B9UJdEh39ym namespace=xmr-btc-swap-mainnet addresses=["/dnsaddr/5555555555555.p"] ttl=7200
Jul 21 23:57:09 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-21 23:57:09  INFO Peer registered peer=xxxxxxxxxxxx namespace=xmr-btc-swap-mainnet addresses=["/dns4/------------------/tcp/9942/p2p/xxxxxxxxxxxx"] ttl=7200
Jul 21 23:57:43 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-21 23:57:43  INFO Peer registered peer=klNBAFX8ns1hsUdiBRhn7EMjxv609Y0HZOdmpS3iUcNRcbS/jmFdAQMRMckoBvD0 namespace=xmr-btc-swap-mainnet addresses=["/onion3/xxxxxxxxxxxx:9941"] ttl=7200
Jul 22 00:00:09 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-22 00:00:09  INFO Peer registered peer=3cSuqmlD1vLey+SjrvGNSghdndGbgWrCV3CiPr3U98v3H1qF2wGU4B9UJdEh39ym namespace=xmr-btc-swap-mainnet addresses=["/dnsaddr/5555555555555.p"] ttl=7200
Jul 22 01:57:09 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-22 01:57:09  INFO Registration expired peer=xxxxxxxxxxxx namespace=xmr-btc-swap-mainnet addresses=/dns4/------------------/tcp/9942/p2p/xxxxxxxxxxxx ttl=7200
Jul 22 01:57:43 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-22 01:57:43  INFO Registration expired peer=klNBAFX8ns1hsUdiBRhn7EMjxv609Y0HZOdmpS3iUcNRcbS/jmFdAQMRMckoBvD0 namespace=xmr-btc-swap-mainnet addresses=/onion3/xxxxxxxxxxxx:9941 ttl=7200
Jul 22 02:00:09 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-22 02:00:09  INFO Registration expired peer=3cSuqmlD1vLey+SjrvGNSghdndGbgWrCV3CiPr3U98v3H1qF2wGU4B9UJdEh39ym namespace=xmr-btc-swap-mainnet addresses=/dnsaddr/5555555555555.p ttl=7200
Jul 22 03:06:11 yyyyyyyyyyyy99999.com rendezvous-server[3393742]: 2022-07-22 03:06:11  INFO Peer registered peer=12D3KooWSdwoAG4nwW314u8cJWANoyyGTLRb2BYgfm2peDJfv6FK namespace=xmr-btc-swap-mainnet addresses=["/dns4/j7zw6nzwrixuy6bat4cucdeg5uj3msoj33emgkpohtxzndpx2wiopoyd.onion/tcp/9939"] ttl=7200

```
**Platform (please complete the following information):**

- ASB
- 0.10.1
- Ubuntu

**Comment by delta1** [comment]
Hey thanks for reporting, will take a look

**Comment by delta1** [comment]
Hey @SIEVEofEratosthenes I've been digging into this, and I'm not able to reproduce the issue. 

We've got a [passing unit test here](https://github.com/comit-network/xmr-btc-swap/blob/b371827b863a26dc3bdfc7dce4b032989ad7580d/swap/src/asb/network.rs#L418), and when I tested locally my ASB was re-registering at the given TTL (which defaults to 2 hours) 

I suspect that those registered ASBs have just gone offline, at which point their registration expires when the TTL is reached. 

You could test by leaving your ASB running and checking that it does re-register every 2 hours. 

Do you want to share your rendezvous multiaddr and I'll try it out too?

**Comment by SIEVEofEratosthenes** [comment]
Thanks a bunch for looking into this. I checked again, and the ASB instance did not re-register, but I was able to begin conducting a swap with the provider, showing that it was in fact online.   I also have coded a "ping" client that monitors the uptimes of the providers, and I'm seeing a ping from the host on my ASB every 10 minutes. Here are some screenshots of the Rendezvous server where it shows registration expired, and the following screenshot shows I was able to conduct a swap with one of them. You can verify this by the p2p hash. 

![rendezvous](https://user-images.githubusercontent.com/89244333/181113883-d9051cab-9368-4f29-bc76-937f7e7edbee.png)
![swap](https://user-images.githubusercontent.com/89244333/181113887-f66e01cf-1ca7-4c0e-b081-674e463938b1.png)

Yeah, if you want to try it out, the rendezvous server is:

```
/dns4/eratosthen.es/tcp/7798/p2p/12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs
```

Appreciate you spending the time with this.

**Comment by delta1** [comment]
I will try to reproduce this with your rendezvous

**Comment by SIEVEofEratosthenes** [comment]
![Uploading Screenshot_2022-07-27_19-29-26.png…]()

**Comment by delta1** [comment]
> ![Screenshot_2022-07-27_19-29-26](https://user-images.githubusercontent.com/89244333/181389791-34018a93-9235-4231-9acb-71aad5aea9f0.png)

Yeah sorry I couldn’t keep it online yesterday, will set it up today and stay connected

**Comment by delta1** [comment]
Hey so I started and left the ASB for over an hour, it registered immediately, and then re-registered after an hour. Which is expected, the initial TTL is 2h and the ASB code re-registered at TTL / 2 

```
2022-07-28T09:14:31.715119Z  INFO Successfully registered with rendezvous node
2022-07-28T09:19:31.717398Z DEBUG Lost connection to peer: Connection error: I/O error: connection is closed peer=12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs address=/dns4/eratosthen.es/tcp/7798/p2p/12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs
^T2022-07-28T10:14:32.774995Z DEBUG New connection established peer=12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs address=/dns4/eratosthen.es/tcp/7798/p2p/12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs
2022-07-28T10:14:33.180945Z  INFO Successfully registered with rendezvous node
2022-07-28T10:19:33.225879Z DEBUG Lost connection to peer: Connection error: I/O error: connection is closed peer=12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs address=/dns4/eratosthen.es/tcp/7798/p2p/12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs
```

**Comment by delta1** [comment]
Without a way to reproduce this I'm not sure what I can do for now. Will be releasing a new version soon, but I guess there's no way to get operators to upgrade :shrug:

**Comment by SIEVEofEratosthenes** [comment]
Yes. Sorry for my late response. I saw the expiry and re-registration. Okay. I'll reach out to him and let him know to upgrade. Appreciate the time you spent very much.
