### ISSUE TITLE
Monero balance too low to conduct swap...Latest Preview version

### ISSUE THREAD

**Issue by xmrswapme** [comit-network/xmr-btc-swap#1084]
**Describe the bug**
I have plenty of monero in my wallet, my maximum is 0.0045 BTC ~ .65 XMR, my minimum is 0.0002 BTC. I get the following errors in the latest preview version

**Lost/trapped Funds**
No

**Debug logs**
2022-08-02T18:57:46.599355617Z  INFO Initialized Monero wallet monero_balance=0.826286435921 XMR
2022-08-02T18:58:05.704608738Z  WARN Your Monero balance is too low to initiate a swap, as your minimum swap amount is 0.00020000 BTC. You could at most swap 0.00000000 BTC

**Platform (please complete the following information):**

ASB
- Software Version: latest preview
- Operating System: Ubuntu

NOTE: Monero v0.18.0 daemon and rpc-wallet are installed on the server which ASB connects to.

**Comment by delta1** [comment]
Hey @xmrswapme thanks for reporting, will take a look

**Comment by delta1** [comment]
I think this depends on your `ask_spread` as well as the current exchange rate do you have those figures?

**Comment by delta1** [comment]
@xmrswapme fixed in #1086 please try the newest preview
