### ISSUE TITLE
Bitcoin wallet broken "ChecksumMismatch"

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#1182]
**Describe the bug**
The bitcoin wallet is disfunctional and can't be initialized.

**Lost/trapped Funds**
Yes or No

**Debug logs**

```
./swap --testnet export-bitcoin-wallet
2022-10-24T16:46:03.72861Z  INFO Logging initialized to /Users/***/Library/Application Support/xmr-btc-swap/cli/testnet/logs
Error: Failed to initialize Bitcoin wallet

Caused by:
    ChecksumMismatch
```

**Platform (please complete the following information):**

- CLI
- Software Version: HEAD (preview)
- Operating System: M2 Mac OS

**Comment by delta1** [comment]
I think I hit this before - is it possible you tried to open a mainnet wallet with the `--testnet` flag or vice versa?

**Comment by delta1** [comment]
This comes from the call into [`bdk::Wallet::new`](https://docs.rs/bdk/latest/bdk/wallet/struct.Wallet.html#method.new) that says 

`The only way this can fail is if the descriptors passed in do not match the checksums in database` 

I suspect the wallet you're trying to open is for the other network.

**Comment by delta1** [comment]
> M2 Mac OS 

NOICE

**Comment by binarybaron** [comment]
> I hit this before - is it possible you tried to open a mainnet wallet with the `--testnet` flag or vice versa?

I don't think so. Why would that be the case?

**Comment by binarybaron** [comment]
Can you reprodue this issue? It doesn't occur on the latest stable release (https://github.com/comit-network/xmr-btc-swap/releases/tag/0.11.0). Only on preview.

Maybe it was caused by the upgrade to bdk 0.23 https://github.com/comit-network/xmr-btc-swap/commit/ef7922f898191cfcf1e843af70c6a010a9d733d7 ?

**Comment by delta1** [comment]
> > I hit this before - is it possible you tried to open a mainnet wallet with the `--testnet` flag or vice versa?
> 
> I don't think so. Why would that be the case?

I’ve had it happen before - the testnet descriptor from the seed would be different to mainnet

**Comment by delta1** [comment]
> Can you reprodue this issue? It doesn't occur on the latest stable release (https://github.com/comit-network/xmr-btc-swap/releases/tag/0.11.0). Only on preview.
> 
> Maybe it was caused by the upgrade to bdk 0.23 [ef7922f](https://github.com/comit-network/xmr-btc-swap/commit/ef7922f898191cfcf1e843af70c6a010a9d733d7) ?

I will try to reproduce. So the same wallet file you created with 0.11 doesn’t open with preview? I will test the same and confirm - it is possible there was a breaking change in bdk although that upgrade was relatively simple.

**Comment by delta1** [comment]
Reproduced the issue but it appears to only occur with a testnet wallet :shrug: 

Generated new mainnet and testnet wallets with 0.11, then called `balance` with the current preview [40d0a2631](https://github.com/comit-network/xmr-btc-swap/releases/tag/preview) binary

```bash
/tmp/swap-test                                                                                     10:54:26
> sha256sum swap*
a99094145d944d57a035494fed63c22d666e0f0fc75edb519ed0b32f7f47de92  swap-0.11.0
66a8b3d76f76f41f2f3ef81918c48b358a816782579aa8a7a698a91f0f9d4d65  swap-preview-40d0a2631

/tmp/swap-test                                                                                     10:54:38
> ls
swap-0.11.0  swap-preview-40d0a2631

/tmp/swap-test                                                                                     10:54:46
> ./swap-0.11.0 --debug --data-base-dir . balance
2022-10-25T08:55:29.190099811Z  INFO Logging initialized to ./mainnet/logs
2022-10-25T08:55:29.190192692Z DEBUG No seed file found, creating at ./mainnet/seed.pem
2022-10-25T08:55:29.190235433Z  INFO Parent directory does not exist, creating recursively directory=./mainnet/seed.pem
2022-10-25T08:55:30.830341067Z  INFO Checked Bitcoin balance balance=0.00000000 BTC

/tmp/swap-test                                                                                  6s 10:55:30
> ./swap-0.11.0 --testnet --debug --data-base-dir . balance
2022-10-25T08:55:43.252661818Z  INFO Logging initialized to ./testnet/logs
2022-10-25T08:55:43.252715807Z DEBUG No seed file found, creating at ./testnet/seed.pem
2022-10-25T08:55:43.252754224Z  INFO Parent directory does not exist, creating recursively directory=./testnet/seed.pem
2022-10-25T08:55:47.146984479Z  INFO Checked Bitcoin balance balance=0.00000000 BTC

/tmp/swap-test                                                                                  7s 10:55:47
> ./swap-preview-40d0a2631 --debug --data-base-dir . balance 
2022-10-25T08:56:02.267624465Z  INFO Logging initialized to ./mainnet/logs
2022-10-25T08:56:02.267723837Z DEBUG Reading in seed from ./mainnet/seed.pem
2022-10-25T08:56:04.807634381Z  INFO Checked Bitcoin balance balance=0.00000000 BTC

/tmp/swap-test                                                                                  4s 10:56:04
> ./swap-preview-40d0a2631 --testnet --debug --data-base-dir . balance
2022-10-25T08:56:25.393365044Z  INFO Logging initialized to ./testnet/logs
2022-10-25T08:56:25.393496488Z DEBUG Reading in seed from ./testnet/seed.pem
Error: Failed to initialize Bitcoin wallet

Caused by:
    ChecksumMismatch
```

**Comment by delta1** [comment]
`git-bisect` indicates this was the breaking change: https://github.com/comit-network/xmr-btc-swap/pull/1116 

Which is *somewhat* expected since that was bdk 0.16 -> 0.22 

I will try see what changed in BDK to cause that, but besides that I think this issue shows it's worth having a test in CI to test opening wallets created with the previous release version.

**Comment by delta1** [comment]
Tracked this down to this change: https://github.com/bitcoindevkit/bdk/issues/578 

I've got a failing integration test done, and working on a migration/fix
