### ISSUE TITLE
Use unlocked Monero balance to calculate `max_bitcoin_for_monero`

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#1192]
**Describe the bug**
We need to use the unlocked Monero balance instead of normal Monero balance to calculate `max_bitcoin_for_monero`.

**Lost/trapped Funds**
Yes or No

**Debug logs**
Please post your debug logs. You find them in:
Linux: /home/<user>/.local/share/xmr-btc-swap/logs
OSX: /Users/<user>/Library/ApplicationSupport/xmr-btc-swap/logs

**Platform (please complete the following information):**

- CLI or ASB [eg. CLI]
- Software Version [e.g. 0.8.3]
- Operating System: [e.g. Ubuntu]

**Comment by delta1** [comment]
Nice, I was wondering about this

**Comment by delta1** [comment]
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#get_balance
