### ISSUE TITLE
Avoid wallet-rpc error message when watching for txlock (Bob)

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#122]
## Problem

On Bobs side we see multiple of these errors on the `monero-wallet-rpc` when starting to watch for the txlock transaction:

```
2021-01-06 06:04:54.490	E !ok || (res.txs.size() != 1 && res.txs_as_hex.size() != 1). THROW EXCEPTION: error::wallet_internal_error
```

This error happens when we query to see Alice's transaction, but Bob's wallet has not picked it up yet - i.e. it did not arrive in the mempool of the node yet. I was not expecting this in my current setup (both parties use the same node but different wallet-rpc instances), but from the Debug log of the swap I can see:

```
2021-01-06T00:15:22.903280Z DEBUG monero_harness::rpc::wallet: transfer RPC response: {
  "error": {
    "code": -1,
    "message": "Failed to get transaction from daemon"
  },
  "id": "1",
  "jsonrpc": "2.0"
}
```

It might be a bit confusing to users, but it is not harmful. Eventually the transaction is found and is checked for confirmations.

## Goal

Don't confuse the user with cryptic errors.

## Proposal

One way to remove it would be to just give Bob's wallet a delay for looking for the confirmations. 
Generally, since we expect at least 10 confirmations we don't have to check immediately and every second.

**Comment by D4nte** [comment]
> Don't confuse the user with cryptic errors. 

The error is coming from monero-wallet-rpc, right? I think the action items should just be adding a "known limitations" section in the readme and mention that this harmless.

**Comment by thomaseizinger** [comment]
Closing because we are going to hide `monero-wallet-rpc` from the user so they shouldn't see this at all.
