### ISSUE TITLE
Failed to make quote: overflow

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#1258]
**Describe the bug**
My testate ask I'm running locally is failing to respond with quotes. Perhaps this is related to the change you recently made @delta1 ?

**Lost/trapped Funds**
No

**Debug logs**
```
Failed to make quote: Bitcoin price (10200000000 BTC) x Monero (38.914307699663 XMR) overflow peer=12D3KooWB2dYJ1X6iefNmEbh7cEKHmZPFEraHjKMVyWb254DLo6g
```
**Platform (please complete the following information):**

- ASB (master head)

**Comment by binarybaron** [comment]
Nevermind. Probably related to the high price I set

**Comment by delta1** [comment]
Yeah before that fix this would have been a panic/crash instead of error
