### ISSUE TITLE
[SP] Swap Website

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#130]
Service Provider (SP) hosts a website for users to use the service. When I navigate to the swap website, as a user...

- [ ]     I can select the Bitcoin quantity I want to sell.
- [ ]     I can see an approximate Monero quantity that the SP is willing to trade.
- [ ]     I can get the swap cli command to run to execute the swap with the SP with the chosen quantities.
- [ ]     I can navigate to the installation instructions/binaries of the swap CLI.

**Comment by thomaseizinger** [comment]
Closing because it is an epic from a previous project.
