### ISSUE TITLE
[SP] Automated Swap Backend

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#131]
The Service Provider (SP) also runs a backend that has the role to execute swaps. The backend...

- [x] https://github.com/comit-network/xmr-btc-swap/pull/174 WIP - automatically executes a swap when reached via the p2p interface.
- [x] gets any related configuration items for a config file, the config file has reasonable defaults.
- [ ] provides an API to allow the website to access the current rate.
- [ ] uses kraken mid-market rate as rate.
- [ ] uses an up-to-date rate when locking the Bitcoin asset.
- [ ] does not proceed with swap execution if predicted Bitcoin quantity to sell is above a configurable ratio of total balance.
- [ ] uses bitcoind wallet as Bitcoin Wallet.
- [x] uses monero-wallet-rpc as Monero Wallet.
- [ ] prints Bitcoin cancellation, Bitcoin punishment transactions when computed
- [ ] prints Monero (refund) private key when the protocol allows (Bitcoin refunded)
- [ ] can run several swaps concurrently.
- [ ] Bonus: bundles the swap website, allowing the SP operator to just proxy from their favourite webserver.

**Comment by da-kami** [comment]
Notes on `can run swaps concurrently`, after working on https://github.com/comit-network/xmr-btc-swap/pull/147 I see the following issues to be resolved to make concurrent swaps happen:

* Separate `EventLoop` and `EventLoopHandle` - I think we will need this to make concurrent swaps possible. We should be able to drive a swap through a handle without creating a new `EventLoop`. I think the `EventLoop` should live in the factory, while the handles live in each swap. (Currently the `EventLoop` is returned upon creating a swap.)
* Don't just have one `swap_id` in the `Factory` but have a list of swaps.
* Make swaps identifiable in the network communication.

**Comment by D4nte** [comment]
Regarding `can run swaps concurrently`, it also means concurrent access to the DB. I think we should do #133 to not end up fixing the db concurrent access twice.

**Comment by thomaseizinger** [comment]
Closing because epic from previous project.
