### ISSUE TITLE
Migrate database from sled to SQLite

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#133]
As previously pointed out [2] we should avoid going to mainnet with sled. While this project does not intend to go to mainnet, we are putting in place a number of features (`list` and `manual-abort` command that require evolving the database. Now is a good time as ever to migrate to Sqlite for mainnet readiness)

- [2] https://lists.comit.network/pipermail/comit-dev/2020-November/000018.html

**Comment by thomaseizinger** [comment]
Unfortunately not a priority for now.
