### ISSUE TITLE
Migrate libp2p implementation from response channel usage to one shot protocols

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#134]
Currently, Alice replies through response channel. They become invalid if the connection with Bob drops (while waiting for a transaction to be confirmed for example). By moving away from response channels, we:

- increase the number of scenarios where the swap can be resumed upon a restart. We currently abort the swap if an issue occurs and the next message is Alice responding to Bob
- Improve robustness, we are currently not able to proceed with testnet swap across this internet due to connection being drop and the current design.

**Comment by D4nte** [comment]
This may not be needed. Another proposal would be to remove `alice::Message2` Meaning that we would not need to hold a response channel.
To be discussed as part of Updating the negotiation protocol.

**Comment by D4nte** [comment]
See #140 for the new proposal.

**Comment by thomaseizinger** [comment]
Is this outdated @D4nte ?

**Comment by D4nte** [comment]
Done with #173
