### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [comit-network/xmr-btc-swap#1341]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by delta1** [comment]
Hi @igibek thanks. I am one of the current maintainers, but unfortunately can't enable that setting. I will ask the repo owners to do so. 

In the meanwhile, you can reach me via email at byron@hambly.dev or on matrix at `@delta1.dev:matrix.org`

**Comment by delta1** [comment]
@igibek - private vulnerability reporting has been enabled on the repo

**Comment by delta1** [comment]
Feel free to reply or reopen.
