### ISSUE TITLE
BCH-XMR Swap

### ISSUE THREAD

**Issue by A60AB5450353F40E** [comit-network/xmr-btc-swap#1424]
It is now possible to support BCH, too.

With the May '22 Bitcoin Cash upgrade, swaps using adaptor signatures and HTLCs are now possible. Bitcoin Cash doesn't have SegWit, so the problem of malleability must be solved in another way: by using covenants to forward the locked BCH to the refund contract.

More information: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/14

Note that there's a 10.5 XMR bounty available to anyone who first implements it: https://bounties.monero.social/posts/37/10-500m-bch-xmr-atomic-swaps

**Comment by delta1** [comment]
Okay.
