### ISSUE TITLE
cross build broken 

### ISSUE THREAD

**Issue by delta1** [comit-network/xmr-btc-swap#1439]
https://github.com/comit-network/xmr-btc-swap/actions/runs/6051537632/job/16423203251 

might be time to just target rust stable instead of keeping an MSRV.

**Comment by binarybaron** [comment]
Any idea what's causing this?

**Comment by binarybaron** [comment]
Just bumping this up to 1.67 should work for the time being but in the long term you are right

https://github.com/comit-network/xmr-btc-swap/blob/5b162368cab7bb17f573cbe206e5f756be1ba914/.github/workflows/build-release-binaries.yml#L55-L59

**Comment by binarybaron** [comment]
Fixed by https://github.com/comit-network/xmr-btc-swap/pull/1440
