### ISSUE TITLE
My btc-xmr swap with provider has been stuck on "Locking BTC" step for 10 hours now, yet to be confirmed

### ISSUE THREAD

**Issue by mike01484** [comit-network/xmr-btc-swap#1454]
Hello, I am having an issue with my swap. Sorry if this is a lame question but any advice would be appreciated.

I am new to unstoppableswap app (using windows app 0.5.2), and I did my first swap Thursday afternoon which was successful and had no issue. However, last night I initiated a swap with same provider the app listed as recommended and deposited the BTC funds to swap for XMR. It's been about 10 hours now since I sent the BTC funds but the provider has yet to confirm the btc TX once. My swap is still on the 1st step of "Locking your Bitcoin". 

Should I cancel the swap (it's still in process and waiting) to start a refund and choose a new swap provider, or is this just an issue on the provider's end and I just need to wait longer for the btc confirmation later today? 

Thanks in advance,
Mike

**Comment by mike01484** [comment]
btw, the btc deposit tx id is: a8666c4c15669595d23b800f3d4ef69e8848d1572111f3a4e9b90900fa263f41

it's been 17 hours now since i deposited and still unconfirmed.

**Comment by mike01484** [comment]
btc was refunded, issue resolved. Thank you.

**Comment by mike01484** [comment]
Thanks, I see. Sorry but one more question, the refund I received to my wallet has been pending for over 2 hours now... was about to head to bed when I made one final check and noticed the funds were still pending. Is this related to the fee issues you guys are having right now? TX id: 5018b9dc693d8d7091970f93f2daf749242fe8a354de68c8337b8439a788bb34

**Comment by delta1** [comment]
yes at that feerate it is low prio at the moment in the mempool. it will eventually get mined, you'll just have to wait for it.


https://mempool.space/tx/5018b9dc693d8d7091970f93f2daf749242fe8a354de68c8337b8439a788bb34
