### ISSUE TITLE
cargo test breaks past Rust 1.76

### ISSUE THREAD

**Issue by nuts-rice** [comit-network/xmr-btc-swap#1602]
**Describe the bug**
`cargo test` isn't building past rustc 1.76
**Lost/trapped Funds**
No

**Debug logs**
Please post your debug logs. You find them in:
![Screenshot from 2024-04-09 17-01-06](https://github.com/comit-network/xmr-btc-swap/assets/5147364/c70afa06-a71f-4e65-a796-69c218be5688)

**Platform (please complete the following information):**
- rust version manger: rustup
- Operating System: Ubuntu

**Comment by delta1** [comment]
Thanks, adding a CI job in #1603 to reproduce and then fix the issue

**Comment by delta1** [comment]
actually fixed by this commit in #1466 

https://github.com/comit-network/xmr-btc-swap/pull/1466/commits/8322f86b64076adc3ff14d2cb44fc3238ae92628
