### ISSUE TITLE
`Draft new release` Github action is failing

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#1645]
See https://github.com/comit-network/xmr-btc-swap/actions/runs/9227114845/job/25388369330

**Comment by delta1** [comment]
should be fixed by https://github.com/comit-network/xmr-btc-swap/pull/1466/commits/904b2ad82993ab354bfd88dad6faee7a24b4fb9f 

which is also bumping the MSRV

**Comment by delta1** [comment]
seems to be fixed now
