### ISSUE TITLE
build binaries action is failing 

### ISSUE THREAD

**Issue by delta1** [comit-network/xmr-btc-swap#1650]
https://github.com/comit-network/xmr-btc-swap/actions/runs/9252686056

**Comment by delta1** [comment]
mostly fixed in #1653 but still an issue to debug with x86_64 apple darwin https://github.com/comit-network/xmr-btc-swap/actions/runs/9253748473/job/25454087243

**Comment by delta1** [comment]
fixed

**Comment by binarybaron** [comment]
awesome, thanks for fixing this. 

Small thing but the name of the uploaded binary is deviating from the other names file names.

[default.swap_preview_Darwin_x86_64](https://github.com/comit-network/xmr-btc-swap/releases/download/preview/default.swap_preview_Darwin_x86_64)

**Comment by delta1** [comment]
PRs welcome :P

**Comment by binarybaron** [comment]
> PRs welcome :P

i'll look into it :)

**Comment by binarybaron** [comment]
> > PRs welcome :P
> 
> i'll look into it :)

probably fixed with https://github.com/comit-network/xmr-btc-swap/pull/1658 (still waiting for the ci run to complete)
