### ISSUE TITLE
Allow `--change-address` to be omitted to refund Bitcoin back to internal Bitcoin wallet instead of external wallet

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#1696]
When Bob starts a swap he has to provide a "change address" which is set as the Bitcoin refund address.

Bob should be able to ommit the `--change-address` and then the Bitcoin refund address should be set to an address of the internal Bitcoin wallet.

**Comment by Einliterflasche** [comment]
This may cause confusion. Perhaps we should allow a different, more explicit flag like `--refund-to-internal-wallet`

**Comment by binarybaron** [comment]
> This may cause confusion. Perhaps we should allow a different, more explicit flag like `--refund-to-internal-wallet` 

You're right that's better. Good idea
