### ISSUE TITLE
Check balances prior to swapping to avoid starting a swap that cannot be fulfilled 

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#175]
## Problem

Neither Alice nor Bob have a balance check that compares the swap amount with the own available funds prior to swapping. 

## Goal

The swap-tool should ensure that only swaps which can be fulfilled are allowed to be triggered.

**Comment by D4nte** [comment]
This is already tracked for Alice in #131

**Comment by da-kami** [comment]
> This is already tracked for Alice in #131

I disagree. https://github.com/comit-network/xmr-btc-swap/issues/131 only touches the ASB (automated swap backend) and is not concerned about the CLI.

Additionally #131 only states `does not proceed with swap execution if predicted Bitcoin quantity to sell is above a configurable ratio of total balance. ` which is a completely different problem.
 
The problem I am describing is ensuring that either party has enough funds to proceed with locking. Especially on the ASB (automated swap backend) side this is critical for UX, because if Alice does not have the funds to find after Bob does then Bob might fund without her being able to proceed. 
This goes towards the previous strategy of Nectar to do some bookkeeping to ensure funds are available. We don't have to do that right away but should keep it in mind.

Concerning the CLI, there should be a better error message when Bob has insufficient funds. Note that the behavor will depend on the decisions taken in https://github.com/comit-network/xmr-btc-swap/issues/193

**Comment by thomaseizinger** [comment]
1. CLI should immediately exit if not enough balance.
2. ASB should send error for quote request if not enough balance.
3. CLI should exit if error from quote request.

**Comment by thomaseizinger** [comment]
The swap-cli handles this now with #236 by waiting for funds on startup if the balance is 0.

**Comment by thomaseizinger** [comment]
I think both parties now have balance checks.
