### ISSUE TITLE
Wallet initialization per command and initial setup

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#181]
## Problem

At the moment we always create both wallets no matter what command we execute. That is not user friendly, as some commands only need the bitcoin wallet. 

However, the initial setup is attached to this problem as well, because currently the initial configuration is tied to the `init_wallets` function. This needs some untangling. 

## Goal

* Start only the wallet(s) needed for each command. 
* Ask the user for required configuration information when needed (i.e. not for the complete configuration)

**Comment by thomaseizinger** [comment]
Closing because not a feature and can be fixed whenever pressing.
