### ISSUE TITLE
Bdk: electrum_client::SharedIoError when Alice redeem transactions and most likely when bob refunds

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#186]
`Electrum(AllAttemptsErrored([SharedIOError(Custom { kind: ConnectionAborted, error: "CloseNotify alert received" })]))`

**Comment by thomaseizinger** [comment]
Theory 1:

This happens because are using bdk's sync interface within an async context.

**Comment by thomaseizinger** [comment]
Theory 1 is invalidated. The error is only made sharable among threads but actually happens as part of an IO error further down.

**Comment by thomaseizinger** [comment]
The error `"CloseNotify alert received"` is created by rustls and happens when the server stops sending us data.

**Comment by thomaseizinger** [comment]
Theory 2:

There is already a new version of electrum-client available (0.6.0), maybe upgrading to that fixes the issue.

**Comment by thomaseizinger** [comment]
Theory 3:

This only happens after longer periods of time. We have a persistent connection to the block explorer. It might be that the block explorer has simply closed the connection and we just only notice the next time we need to talk to it.

**Comment by thomaseizinger** [comment]
I think I solved it.

We maintain a persistent connection to the block explorer which likely gets closed after some amount of time. The client actually has functionality to re-connect if that happens. Unfortunately, there seems to be a [bug](https://github.com/bitcoindevkit/rust-electrum-client/issues/47) which makes this logic not actually kick in. The following patch should fix that:

```diff
From 61d6d52021111d668bf0fdea579771bc6c687921 Mon Sep 17 00:00:00 2001
From: Thomas Eizinger <thomas@eizinger.io>
Date: Mon, 15 Feb 2021 16:04:51 +1100
Subject: [PATCH] Instantiate electrum client with custom config with 2 retries

The default number of retries is 1. Unfortunately, the way this config
value is interpreted doesn't actually lead to a retry. We have to set
it to 2 to actually make it retry.

See https://github.com/bitcoindevkit/rust-electrum-client/issues/47.
---
 swap/src/bitcoin/wallet.rs | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/swap/src/bitcoin/wallet.rs b/swap/src/bitcoin/wallet.rs
index 01da1c7..9f37ced 100644
--- a/swap/src/bitcoin/wallet.rs
+++ b/swap/src/bitcoin/wallet.rs
@@ -12,7 +12,7 @@ use async_trait::async_trait;
 use backoff::{backoff::Constant as ConstantBackoff, tokio::retry};
 use bdk::{
     blockchain::{noop_progress, Blockchain, ElectrumBlockchain},
-    electrum_client::{Client, ElectrumApi},
+    electrum_client::{self, Client, ElectrumApi},
     keys::GeneratableDefaultOptions,
     FeeRate,
 };
@@ -45,7 +45,10 @@ impl Wallet {
         network: bitcoin::Network,
         waller_dir: &Path,
     ) -> Result<Self> {
-        let client = Client::new(electrum_rpc_url.as_str())
+        // Workaround for https://github.com/bitcoindevkit/rust-electrum-client/issues/47.
+        let config = electrum_client::ConfigBuilder::default().retry(2).build();
+
+        let client = Client::from_config(electrum_rpc_url.as_str(), config)
             .map_err(|e| anyhow!("Failed to init electrum rpc client: {:?}", e))?;
 
         let db = bdk::sled::open(waller_dir)?.open_tree(SLED_TREE_NAME)?;
-- 
2.30.0
```

**Comment by thomaseizinger** [comment]
Fixed in https://github.com/comit-network/xmr-btc-swap/issues/160.

**Comment by thomaseizinger** [comment]
Actual upstream fix here: https://github.com/bitcoindevkit/rust-electrum-client/pull/48.
