### ISSUE TITLE
CLI user Bitcoin wallet strategy

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#193]
## Problem

Currently we don't have a coherent strategy and flow for the Bitcoin wallet on the user side (CLI)
Currently the CLI wallet only offers a `deposit` command - which was the minimal requirement to make a swap with the ASB (automated swap backend) possible.
We need a coherent strategy for Bitcoin wallet management, that offers a good usability for the showcase setup.

There are two main questions to be answered:

1. Are we expecting the user to do multiple swaps with the Bitcoin wallet?
2. Should the user be in control of the Bitcoin wallet?

### A - The user is not in control of the wallet

If we answer question 1. with NO, i.e. the user uses the tool for one specific swap (or very sporadic swaps that don't require leaving money in the tool I would suggest the following solution:

1. The user provides a fallback Bitcoin address for each swap.
2. If Bitcoin is refunded the fallback address is used
3. If Bitcoin is redeemed, but the user sent too much funds to the CLI, the remaining Bitcoin are transferred to the fallback-address.
4. When triggering a swap the tool will print an address to be funded that the user has to send funds to.
5. There are no extra commands for the wallet.

Note that this strategy has the risk that, if something goes wrong on the way, it might be hard for the user to recover the funds. 
We might still need withdraw/balance commands for power users, but that could be seen as additional feature.

### B - The user in control of the wallet

If we answer question 1. with YES, i.e. we expect the user to do multiple swaps, it will be in the user's interest to transfer a larger amount of Bitcoin to the swap tool once to save transaction fees. If we expect that the user should have the commands. (This would  give the feel of a power user application.)

### Recommendation: Combined solution

I think the strategies can be combined. If the user specifies a fallback address the remaining funds or refunded Bitcoin can end up on the fallback address. If no fallback is specified it would stay within the swap tool. 

The swap tool offers `deposit`, `balance` and `withdraw` commands but they are not advertised. Power users will find out anyway.

It is not much work to provide the commands (and we might need them anyway for failure scenarios). 
But, to offer a user experience with less interaction we would have to implement scenario A as well.

The hard part is, that if we default to the CLI wallet then user might always default and then has to use the commands. We could do it the other way round - always ask for a fallback address, but power users can specify the one of the swap tool itself. (Bit weird, but coherent...)

## Goal

A coherent Bitcoin wallet strategy, for the CLI that offers best usability for the showcase application.

**Comment by rishflab** [comment]
If we go with strategy A to start with how would the user see the results of the swap. Would we print the balances after the swap is complete?

**Comment by da-kami** [comment]
Moved to https://github.com/comit-network/xmr-btc-swap/discussions/198
