### ISSUE TITLE
Better Error handling for calcuation errors (notably subtractions)

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#194]
## Problem

Currently, if we try to swap amounts that are smaller than the transaction fee, we run into an overflow error:

https://github.com/comit-network/xmr-btc-swap/blob/e11fe4fe8115cb2ede949cfa2d162cab2f10ea5c/swap/src/bitcoin/transactions.rs#L241

This is not a scenario that should be very common in production - unless people want to "give the tool a try" before actually using if for larger amounts ;)

I would recommend to handle errors on calculations in a more explanatory way using context rather than changing the logic. This might not only concern the code part stated as example above but should be done for all calculations where it is important to give the user context. 

## Goal

The user should not get an overflow error that does not explain why the application failed.

**Comment by thomaseizinger** [comment]
1. Use clippy to find all places where arithmetic can underflow / overflow.
2. Replace with checked_{add,sub} with meaningful error messages.

**Comment by thomaseizinger** [comment]
Labeled as bug because the panic will only happen in debug mode, a release build will underflow and cause surprising behaviour for the user.

**Comment by da-kami** [comment]
If we enforce #445 calculation problems of too low amounts should be gone. Can potentially be close after #445 was implemented.
