### ISSUE TITLE
Watch For Deposit

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#196]
## Problem
The buy-xmr tool generates and displays a bitcoin address for the user to fund. These funds are used to buy Monero. Currently we are manually checking that these funds have arrived before commencing the swap. This does not fit with the goal of providing a streamlined UX.

## Potential Solution

**Assumption: We do not really care how the buy-xmr tool is funded. All that matters is that is has enough funds to execute the swap.**

The buy-xmr tool should watch for the funds and automatically commence the swap when they are confirmed.

Loop on `bdk_wallet.get_balance()` until the balance is sufficient for the swap.

### Potential Issues

1. `get_balance()` requires the wallet to be synced. Syncing could take a while.
2. The `get_balance` API doesn't mention anything about UTXO confirmations. The swap could begin execution but fail when it comes to building/publishing/ waiting for TxLock to confirm.

**Comment by da-kami** [comment]
This ticket touches topics related to: 
https://github.com/comit-network/xmr-btc-swap/issues/193
https://github.com/comit-network/xmr-btc-swap/issues/175
