### ISSUE TITLE
Polling for changes to balance / transactions does not scale

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#202]
## Problem

At the moment, when watching for transactions, we bombard the Bitcoin/Monero setup by checking every second. This is currently hardcoded.

## Goal

A scalable solution for waiting until a certain event (transaction included, balance changed, etc)

**Comment by thomaseizinger** [comment]
Replaced by https://github.com/comit-network/xmr-btc-swap/issues/295.
