### ISSUE TITLE
No sys dependencies needed when running the CLI

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#208]
When building the project on the raspberry I noticed that we currently have two dependencies, `openssl` and `protobuf`, which might also have to be available at runtime.

I temporarily solved this by installing the necessary libraries on the raspberry:

```
# install openssp dependencies
sudo apt install -y libssl-dev
# install protobuf dependency
sudo apt install -y protobuf-compiler
```

In order to allow easy use of the CLI we have to ensure that there are no external dependencies.

**Comment by D4nte** [comment]
Theses dependencies are only needed to build the project. This is why they are postfixed with `-dev` and `-compiler`.
Did you try to uninstall them and run the binary?

**Comment by thomaseizinger** [comment]
> Theses dependencies are only needed to build the project.

Are you certain about this? `-dev` just means that we are installing the _headers_ in addition to the shared library. Usually that is necessary because some project wants to **link** against this shared library which implies that the library still needs to be present at runtime.

**Comment by thomaseizinger** [comment]
https://github.com/comit-network/xmr-btc-swap/pull/218 takes care of the openssl dependency.

I couldn't find any mention of the protobuf compiler within the dependency tree. Are you sure that this one is required?
