### ISSUE TITLE
Cleanup test setup when watching for balance in production

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#217]
With https://github.com/comit-network/xmr-btc-swap/pull/216 we added a loop to make sure the wallet has caught up with the balance in the test setup.

Once we implement watching for deposit https://github.com/comit-network/xmr-btc-swap/issues/196 we should remove the code added by https://github.com/comit-network/xmr-btc-swap/pull/216 and ensure we use the production code for waiting for the balance to catch up.

**Comment by thomaseizinger** [comment]
This seems to be no longer valid.

The premise was that we might be able to re-use the 'watch for deposit' functionality but that turned out not to be true, hence closing this.
