### ISSUE TITLE
Swap demo website MVP

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#240]
## Summary of current state of CLI/ASB setup

CLI behaviour:

1. Run the swap tool (no command/parameters needed, default to demo ASB)
2. Send as much BTC as you want to CLI to be swapped
3. The swap starts once the BTC "deposit" tx is in mempool

The demo ASB has the following restrictions:

1. Limit swaps to max 0.5 XMR

## Website MVP

The MVP does not have to display a rate but a static webpage is sufficient to get the user started. 

The user needs the information:

1. Where to download the CLI binary 
2. A field where the user can enter the XMR address where the funds should be retrieved (so that copy-able command can be generated)
3. Copy-able command to run the CLI (e.g "open a terminal and run `./swap_cli buy-xmr --receive-address [xmr_address]`")
4. What is expected once the CLI is started (e.g. "Transfer 0.001 BTC that will be swapped")

**Comment by thomaseizinger** [comment]
We concluded that for now we are not going to build a website.
