### ISSUE TITLE
MacOS release binary doesn't work

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#251]
Trying to execute the binary results in an exec error.

**Comment by rishflab** [comment]
Building the binary with the same command as the CI works locally

**Comment by thomaseizinger** [comment]
Thanks for re-opening. I was thinking it might be the Rust version but that one is pinned in our repository. Any ideas on what this could be?

**Comment by thomaseizinger** [comment]
It might be because we are using BSD tar to pack the binary, same as why the cache workflow didn't work for a long time on MacOS.

Try to use gnu-tar on Mac. It is available as the gtar binary if I am not mistaken!

**Comment by rishflab** [comment]
> It might be because we are using BSD tar to pack the binary, same as why the cache workflow didn't work for a long time on MacOS.
> 
> Try to use gnu-tar on Mac. It is available as the gtar binary if I am not mistaken!
tried using gtar and that didn't help

**Comment by thomaseizinger** [comment]
> tried using gtar and that didn't help. the checksum is the same regardless of whether I use gtar or the Mac OS default tar extractor.

Did you try _packing_ it with gtar on CI?

> The locally build binary has a different checksum to the CI build binary but I guess that is expected?

Unfortunately yes. Getting Rust binaries to be reproducible is quite tricky.
