### ISSUE TITLE
Have a debug log file per swap and print its path to the user on startup

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#278]
If stuff doesn't work for users, it would be good to have the logs even if they didn't pass `--debug`. We should configure tracing to always send the debug logs to a file.

The log file should probably be per swap.

Need to figure out how we can compose tracing subscribers because I think we can only set one.

**Comment by da-kami** [comment]
We should definitely do this! At the moment users don't even know their own peer-id so it is impossible to match swaps on the ASB side. I don't think the peer-id should be displayed to users but we should for sure have a logfile that users can just send us.

**Comment by rishflab** [comment]
This is how I am planning on doing this:

- [ ]  a span(swap id) for each swap
- [ ]  passing a file writer/ appender to the tracing subscriber
- [ ]  the file writer should search the log statement for the swap id and append to the appropriate file based off this swap id

**Comment by thomaseizinger** [comment]
We only need to do this for the CLI, so I am not sure we need to go down the `span` route because the whole invocation of the CLI is scoped to a single swap.

The way I see it is that the main problem to solve is how we can send some log output (INFO level) to the console but also send everything to a file.

Maybe it is good enough to start with to just scope the log-file per invocation? Properly scoping it to per swap would mean a `resume` should probably append to the one that was originally created.

**Comment by rishflab** [comment]
> Maybe it is good enough to start with to just scope the log-file per invocation? 

Ah ok this is a lot simpler than I imagined. Should be pretty easy.
