### ISSUE TITLE
Alice has problems redeeming 

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#294]
Scenario:

1. Bob locks BTC
2. Alice locks XMR
3. Alice runs into Electrum error when redeeming
4. Bob runs into Electrum error when watching for redeem

Alice's error:

```
Mar 05 12:50:46.784 DEBUG swap{id=3f9ed55a-99f6-4eef-959d-e32e3877efd2}: swap::bitcoin::wallet: Received protocol error "missing transaction" from Electrum, retrying...
Mar 05 12:50:48.689 DEBUG swap{id=3f9ed55a-99f6-4eef-959d-e32e3877efd2}: swap::bitcoin::wallet: Received protocol error "missing transaction" from Electrum, retrying...
Mar 05 12:50:50.493 DEBUG swap{id=3f9ed55a-99f6-4eef-959d-e32e3877efd2}: swap::bitcoin::wallet: Received protocol error "missing transaction" from Electrum, retrying...
Mar 05 12:50:52.302 DEBUG swap{id=3f9ed55a-99f6-4eef-959d-e32e3877efd2}: swap::bitcoin::wallet: Received protocol error "missing transaction" from Electrum, retrying...
Mar 05 12:50:54.102 DEBUG swap{id=3f9ed55a-99f6-4eef-959d-e32e3877efd2}: swap::bitcoin::wallet: Received protocol error "missing transaction" from Electrum, retrying...
Mar 05 12:50:55.907 DEBUG swap{id=3f9ed55a-99f6-4eef-959d-e32e3877efd2}: swap::bitcoin::wallet: Received protocol error "missing transaction" from Electrum, retrying...
```

On Alice's (ASB) side this is a severe problem where we print to the logs about every half second spamming the logs really fast. Eventually the ASB restarts (at the moment I am not sure what causes the restart, but it could be systemd picking up the log load?).

Bob's error log:

```
 Monero lock tx has 10 out of 10 confirmations txid=d3165221823977a2c0cadb9e5cd59a0b04c95c46ec6023dfc7a8c98f6656b0e0
Error: Transient errors should be retried

Caused by:
    Electrum client error

```

Lock transaction hashes where this problem was recorded (Bob):

* https://blockstream.info/testnet/tx/3e305e6895211f974718d3ad83e0649d3a090a726f3773c9dc415fc9888a9e24
* https://monero-stagenet.exan.tech/search?value=d3165221823977a2c0cadb9e5cd59a0b04c95c46ec6023dfc7a8c98f6656b0e0

Investigation needed why Alice runs into this error - is it load related (i.e. we spam the public Electrum instance too much) or is it related to other problems (e.g. specific addresses, ...).

**Comment by rishflab** [comment]
Got a feeling it is because we are spamming the public instance too much. We are checking for the tx's every second for every on going swap. Maybe doing this  #296 might help reproduce the error so we can figure out why it is happening?

**Comment by da-kami** [comment]
Fixed with https://github.com/comit-network/xmr-btc-swap/pull/307 and https://github.com/comit-network/xmr-btc-swap/pull/321
