### ISSUE TITLE
ASB is putting heavy load on public electrum node

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#295]
## Problem

The ASB  is putting heavy load on public electrum node when multiple swaps are triggered. There is a risk that the ASB will be disconnected/limited from public node access

## Solution

Use the subscription-based API of electrum and refactor `bitcoin::Wallet` to answer lookups based on local data that is periodically updated using the incoming notifications from electrum.

**Comment by thomaseizinger** [comment]
> Limit sync() and rest api calls

Just checked and we never call `sync` as part of a swap. We directly use the electrum-client for that so only the 2nd part of this bullet point is valid.
