### ISSUE TITLE
Electrum error upon startup of ASB

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#300]
When automatically starting the ASB we ran into this error:

```
Mar 08 23:17:21.519  INFO swap::trace: Initialized tracing with level: debug
Mar 08 23:17:21.519  INFO swap::asb::config: Using config file at default path: /var/external/asb/run/asb-config/config.toml
Mar 08 23:17:21.520 DEBUG swap::database: Opening database at /var/external/asb/run/asb-data/database
Mar 08 23:17:21.564 DEBUG swap::seed: Reading in seed from /var/external/asb/run/asb-data/seed.pem
Error: Failed to init electrum rpc client: IOError(Custom { kind: Other, error: "failed to lookup address information: Temporary failure in name resolution" })
```

This cause the ASB to be unavailable as systemd service fails, this is dealt with `Restart=on-failure` but we should potentially deal with this error in Rust rather than handling it through systemd?

**Comment by thomaseizinger** [comment]
That looks like something systemd should deal with. That is an error in the DNS resolution of your system. I wouldn't implement a retry logic within Rust here.

**Comment by thomaseizinger** [comment]
Closing this based on the previous comment.
