### ISSUE TITLE
Disallow multiple concurrent swaps with same peer 

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#334]
Currently, Alice's (ASB) network communication after swap setup (i.e. learning the encsig) is only related to the peer-id (because that is the only thing we know on the network communication level). This means, that one peer ID can only have one ongoing swap within the ASB at the moment.

However, we do not actively refuse incoming swaps from the same peer-id at the moment. So, if a user triggers a concurrent swap using the same peer ID it will only fail during the execution (because the first `encsig` received will be sent to both executing swaps) but won't be refused.

In order to avoid failing swaps we should disallow triggering multiple concurrent swaps from the same peer.
It is important that the user gets information why the swap was refused. Time to introduce senseful errors when triggering a swap.

**Comment by thomaseizinger** [comment]
@da-kami to split into two tickets.

**Comment by da-kami** [comment]
Unfortunately, just "disallowing" concurrent swaps on Alice's side is not sound enough. Bob has to be able to verify incoming messages as well, to be sure that Alice and him are operating on the same swap.

Thus, we should invest the time into #367 instead.
