### ISSUE TITLE
Linux Binary releases are dynamically linked

### ISSUE THREAD

**Issue by c22** [comit-network/xmr-btc-swap#347]
Not every Linux has libgcc.

```
/opt/xmr-btc-swap # ldd
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
/opt/xmr-btc-swap # ldd asb
        /lib64/ld-linux-x86-64.so.2 (0x7f3533d42000)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by asb)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f3533d42000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f3533d42000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f3533d42000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f3533d42000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by asb)
Error relocating asb: _Unwind_Resume: symbol not found
Error relocating asb: __register_atfork: symbol not found
Error relocating asb: _Unwind_SetIP: symbol not found
Error relocating asb: __res_init: symbol not found
Error relocating asb: _Unwind_GetRegionStart: symbol not found
Error relocating asb: _Unwind_GetTextRelBase: symbol not found
Error relocating asb: _Unwind_FindEnclosingFunction: symbol not found
Error relocating asb: _Unwind_DeleteException: symbol not found
Error relocating asb: _Unwind_RaiseException: symbol not found
Error relocating asb: _Unwind_GetIP: symbol not found
Error relocating asb: _Unwind_GetIPInfo: symbol not found
Error relocating asb: _Unwind_GetDataRelBase: symbol not found
Error relocating asb: _Unwind_SetGR: symbol not found
Error relocating asb: _Unwind_GetCFA: symbol not found
Error relocating asb: _Unwind_Backtrace: symbol not found
Error relocating asb: _Unwind_GetLanguageSpecificData: symbol not found
```

Would the team be open to releasing statically linked binaries?

**Comment by da-kami** [comment]
If you test with `v0.3` please let us know if this is still an issue.

**Comment by c22** [comment]
Yes, the above output was from the current release.

https://github.com/comit-network/xmr-btc-swap/releases/download/v0.3/asb_v0.3_Linux_x86_64.tar

**Comment by da-kami** [comment]
Thanks, that means we should look into it to remove this dependency.

**Comment by thomaseizinger** [comment]
We tried to fix this in https://github.com/comit-network/xmr-btc-swap/pull/371 by compiling everything to musl but that is not as trivial as originally thought.

@c22 If I remember correctly, you ran into this because you wanted to make an Alpine-based Dockerfile. Would one based on f.e. Debian also work for you?

**Comment by c22** [comment]
I'd prefer not to use Debian due to the added weight, but that decision is somewhat orthogonal to this discussion.

When I get some more time, I will go back to the drawing board on this and take a look at other options. Thanks for the consideration.

**Comment by thomaseizinger** [comment]
> I'd prefer not to use Debian due to the added weight

Thanks for clarifying!

I totally understand this desire but I am somewhat tempted to say that perfect is the enemy of good here. I'll start out with a Debian-based Dockerfile just so that we have _something_. We can always optimize from there :)
