### ISSUE TITLE
Alice fails to send `TransferProof`

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#348]
Scenario:

BTC is locked
XMR is locked

Alice fails to send `TransferProof` to Bob with error: 

```
Mar 19 01:18:30 raspberrypi asb[26973]:  ERROR Communication error: Failure with Transfer Proof: Outbound failure: ConnectionClosed peer=12D3KooWSLKSidTtNBYYk7G48quAPLDhtuXixCmAHU4nfLFz6VNg
```

This results in Alice aborting the swap and Bob waiting for refund.

**Comment by da-kami** [comment]
The problem is most likely that the CLI users are behind NAT but for sending the transfer proof Alice dials. This has to be changed.

**Comment by thomaseizinger** [comment]
I think I can easily do this on top of https://github.com/comit-network/xmr-btc-swap/pull/340.
