### ISSUE TITLE
Bad line detection when swap start monero_wallet_rpc

### ISSUE THREAD

**Issue by devbordecraft** [comit-network/xmr-btc-swap#353]
The line detection to detect if monero_wallet_rpc has been started in source swap/src/monero/wallet_rpc.rs:150 can be translated in many different language. So the line detection can't work if the local settings on the computer is configured to be other than english like in french for example.

**Comment by rishflab** [comment]
@devbordecraft what operating system are you on

**Comment by devbordecraft** [comment]
I am using Ubuntu 20.04 with only the French language pack installed.
