### ISSUE TITLE
Panic when TxCancel is initialized

### ISSUE THREAD

**Issue by devbordecraft** [comit-network/xmr-btc-swap#354]
Swap can panic when TxCancel is initialized and the bitcoin amount is too low in source swap/src/bitcoin/cancel.rs:110.
The result of the subtraction can become negative.

**Comment by thomaseizinger** [comment]
Related: https://github.com/comit-network/xmr-btc-swap/issues/194

**Comment by thomaseizinger** [comment]
@devbordecraft We would be very happy about a PR along the lines of what I outlined in the referenced ticket! :)

**Comment by devbordecraft** [comment]
@thomaseizinger Yeah why not, starting working on it :)
