### ISSUE TITLE
Implement discovery based on PeerId

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#362]
This would make it significantly easier for users to connect to alternative makers.

**Comment by thomaseizinger** [comment]
I've worked on this spike for a while now and I think I have some good results: https://github.com/comit-network/xmr-btc-swap/pull/388

Essentially, one only needs to go through the TODOs and fix them. Most importantly:

- Buffer all messages on Bob's side until we are actually connected to Alice
- Only fail the EventLoop on Bob's side if we fail a protocol with Alice and not some random node from the DHT

**Comment by thomaseizinger** [comment]
Relevant discussion: https://github.com/libp2p/rust-libp2p/discussions/2025

**Comment by da-kami** [comment]
Closing this spike, because we are already implementing libp2p rendezvous which will be integrated, so I think no spike is needed anymore.
