### ISSUE TITLE
Recovery of swap failues during runtime

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#375]
The ASB is a long running daemon that a service provider usually does not interact with over longer periods of time. Therefore it would be good if the ASB is able to recover from certain errors during swap execution on its own. 

If a swap fails during execution the ASB may want to retry resuming the swap at a later time. 

The only scenarios where this might be applicable at the moment is blockchain network related issues. E.g. the ASB tries to publish / watch for a transaction but fails with a network error because a public node is not available at the time. 

Implementing this in a robust way includes a more robust transaction handling than currently implemented.

I propose:

- When publishing a transaction we ensure that the transaction is not present on the blockchain yet. If it is we don't publish again but transition accordingly. 
    - The best way of handling this might be just publishing it and handle "already included" publication errors. Needs more discussion.
- When failing to watch for transaction finality we can retry
- We should contact the service provider after X fails (for any tx related issue) because most likely action is required to ensure the ASB's access to synced blockchain nodes. (This may be solved with sentry support, or setting up email support)

--- 

Other scenarios that I thought off, but should not be critical due to the way we handle them already:

- Alice fails to re-open the default wallet after refunding XMR with `generate_from_keys`
    - This should be fine, because we handle this atomically and ensure that the default wallet will be re-opened even if there is an error with creation/draining the refund wallet.
    - This needs more testing on stagenet, because we don't know how long creating and draning the wallet may take (the assumption is that it is done within seconds).
- Punish failure retry is a specific scenario of a transaction "failing" - but it might not be related to network issues. However, I don't think it has to be handle differently.

**Comment by da-kami** [comment]
With the introduction of the `bmrng` channels it seems we have more error pathes that exit the swap execution for the asb:

```
Apr 08 04:58:44 raspberrypi asb[9949]:   INFO swap{id=3e95f27e-f99f-4d9e-ae9e-f50978c67dca}: Current state: xmr is locked
Apr 08 04:58:44 raspberrypi asb[9949]:   WARN No active connection to peer, buffering transfer proof peer=12D3KooWRqVnNWuahKawSSmxQQptGcEApNBFXNodzRv2q6tBvhUW
Apr 08 04:58:44 raspberrypi asb[9949]:  ERROR Swap failed with Failed to send transfer proof: request channel closed swap_id=09309315-1bd4-43f9-b598-84e45c76f90f
Apr 08 05:38:48 raspberrypi asb[9949]:  DEBUG New connection established peer=12D3KooWRqVnNWuahKawSSmxQQptGcEApNBFXNodzRv2q6tBvhUW address=/ip4/192.168.1.2/tcp/53130
Apr 08 05:38:48 raspberrypi asb[9949]:  DEBUG Found buffered transfer proof for peer peer=12D3KooWRqVnNWuahKawSSmxQQptGcEApNBFXNodzRv2q6tBvhUW
Apr 08 05:38:48 raspberrypi asb[9949]:   INFO swap{id=3e95f27e-f99f-4d9e-ae9e-f50978c67dca}: Current state: xmr lock transfer proof sent
Apr 08 05:38:48 raspberrypi asb[9949]:   INFO swap{id=3e95f27e-f99f-4d9e-ae9e-f50978c67dca}: Received encrypted signature
Apr 08 05:38:48 raspberrypi asb[9949]:  ERROR Swap failed with request channel closed swap_id=3e95f27e-f99f-4d9e-ae9e-f50978c67dca
```

These failures can be relevant for re-trying a swap at runtime.

**Comment by bonomat** [comment]
@da-kami : Closed as discussed.

**Comment by da-kami** [comment]
Closed because it is unclear if this feature is actually desirable. If something goes so wrong that the swap cannot act within the boundaries of the state machine, it is acceptable that human interaction is required for now. We should avoid scenarios where we 'bail' out of the state machine as much as possible.
This ticket can be re-visited at a later point if we have a clearer need and requirements for such a retry feature.
