### ISSUE TITLE
Automated CLI testing against ASB

### ISSUE THREAD

**Issue by bonomat** [comit-network/xmr-btc-swap#444]
- [ ] Create a script that tests the CLI against the ASB 
- [ ] Verify that the swap was successful for the ASB
- [ ] Add additional systemd service which runs once per day or after we switch to latest ASB binary.

Script should
1. Pre: downloads the latest CLI binary
2. Start: Triggers a swap against the ASB (locally) - set the receive address to the ASB address, report on failure

**Comment by da-kami** [comment]
Closing this, because it is not an issue that would require any code changes but is more of a devops task and does not have to tracked here.
