### ISSUE TITLE
Create separate struct for subcommands in ASB.

### ISSUE THREAD

**Issue by bonomat** [comit-network/xmr-btc-swap#478]
Since this is suplicated for multiple commands you might want to extract that into a separate struct and use [](https://docs.rs/structopt/0.3.21/structopt/#flattening).

_Originally posted by @da-kami in https://github.com/comit-network/xmr-btc-swap/pull/466#discussion_r627049333_

**Comment by da-kami** [comment]
I think this actually concerned the CLI, fixed as part of #490
