### ISSUE TITLE
Swap Cli crashes if Bitcoin balance is 0.0

### ISSUE THREAD

**Issue by bonomat** [comit-network/xmr-btc-swap#487]
It looks like #481 revealed (or introduced) a bug which makes the CLI fail if Bitcoin balance is 0.0. 

The issue is that `bitcoin_wallet.max_givable(...)` returns an error if the balance is too low and hence we never get to the nicely designed logic which waits for enough bitcoin balance. 

This is a bit unfortunate because there is no way to _recover_ and deposit more BTC into the address  as the bitcoin address will only be printed later on. 

The line which will fail: 
https://github.com/comit-network/xmr-btc-swap/blob/c011e9506238fc7987310844f77d5ba72d2a6423/swap/src/bin/swap.rs#L100

And further down: 
https://github.com/comit-network/xmr-btc-swap/blob/26e0383e173f6c1d7fd364edf2c4cb9f1c82adc0/swap/src/bitcoin/wallet.rs#L328

Error message: 
```
Error: Failed to build transaction

Caused by:
    InsufficientFunds { needed: 53, available: 0 }
```

**Comment by da-kami** [comment]
Do you know how low your balance is? Is it still above dust? (If so we might have to analyze more...)

**Comment by da-kami** [comment]
I just noticed you state

> bug which makes the CLI fail if Bitcoin balance is 0.0.

That should not happen. We either have to fix add a guard to our max_giveable impl, but probably even better upstream a fix to `bdk` - this should not fail I think!
