### ISSUE TITLE
Ensuring compatibility between CLI and ASB versions

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#502]
Relevant discussion: https://github.com/comit-network/xmr-btc-swap/discussions/492

Recommendation: 

Draft-PR that outlines how libp2p versions can help us ensure compatibility.
This should include testing program behavior on protocol version change.

See: https://github.com/libp2p/specs/tree/master/identify

**Comment by thomaseizinger** [comment]
Closing because not directly actionable.

Once #492 yields some concrete ideas, we can discuss over a draft PR.
