### ISSUE TITLE
Abuse of fixed XMR/BTC price

### ISSUE THREAD

**Issue by cimble-code** [comit-network/xmr-btc-swap#557]
First of all, sorry to bother you again with this issue :D
I think Bob can abuse the fixed XMR/BTC price that both parties agree on when Bob connects to Alice. I think to fix this they need to agree on a timeout. If the BTC payment from Bob has not arrived after a certain time, the swap will be cancelled or they will agree on a new more current price.

Because the way it currently works Bob can:
1. connect to the ASB and agree on a price (for example: 0.1 BTC/XMR).
2. Bob can now decide for himself if and when he sends the BTC from his wallet. He now waits 1 hour until the BTC/XMR price reaches 0.15. If after an hour the price dropped Bob simply does not proceed with the swap because if he did he would lose money.
3. Since the two agreed on the price an hour ago, Alice now sells Bob Monero for a price far below the current market price. Bob can sell the Monero again somewhere else and make a profit. Alice has to deal with the implications.

**Comment by da-kami** [comment]
This is implemented, but maybe needs some refining:

https://github.com/comit-network/xmr-btc-swap/blob/master/swap/src/protocol/alice/swap.rs#L72-L93

The timeout is for `Mainnet` is configured as `24 hours`:

https://github.com/comit-network/xmr-btc-swap/blob/master/swap/src/env.rs#L43-L46

This is not optimal. 
I propose the following change: 

1. In `Started` the ASB just waits until the BTC is seen in mempool. There should be a short timeout around that.
2. New state `BitcoinLockTxSeen` for the ASB where we wait for finality of the transaction. We can configure a longer timeout there. 24h is crazy though, I think that should be reduced to 60 mins (i.e. if Bob is not willing to pay transaction fees to be included within the next 6 blocks the swap will fail).

@thomaseizinger thoughts?

**Comment by bonomat** [comment]
This is a very interesting topic and I don't think there is a perfect solution for this. 
Unfortunately we don't have any execution guaranteed nor real atomic transactions cross-chain, so the problem will always exist in one way or the other.
That being said, I don't think it is a big problem at all and there are a few things we considered to mitigate the risk: 

- If Alice (in the role of the maker) is running the ASB for profit (e.g. by arbitraging against a different exchange) she needs to ensure that she adds a big enough spread. While I didn't check the numbers I could assume that a spread of 2-5% could cover a potential shortterm downwards trend.
- As @da-kami pointed out there should be a timeout on the ASB's side in regards to when to continue with the swap. As of now, it's 24h is obviously not the best. 60 minutes (6 blocks) might be better but probably still not perfect. 
 
The person running the ASB needs to come up with a rate + spread and timeout combination she feels comfortable with. She won't be fully protected against being gamed thought. My opinion is that as long as not every user is gaming the ASB, the ASB provider should be fine in the long run. :)
