### ISSUE TITLE
"Please deposit more, not enough BTC to trigger swap" after depositing exact minimum_amount

### ISSUE THREAD

**Issue by cimble-code** [comit-network/xmr-btc-swap#559]
I deposited the exact minimum_amount of BTC to the deposit address but was unable start a swap.

I think the BTC that is needed for fees should be added on top of the displayed minimum_amount.

![Capture](https://user-images.githubusercontent.com/85460331/121809616-01391b80-cc4d-11eb-9556-5e2e863d6368.PNG)

**Comment by thomaseizinger** [comment]
Yep, that is a bit of an inconvenience at the moment.

I am tempted to close this as wont-fix and say it is expected that people know that their transaction needs to pay for fees and trying to swap the exact minimum amount is not going to work.

That said, I'd approve a PR that does a bit fancier calculation and takes into account fees as part of the `determine_btc_to_swap` function.

**Comment by binarybaron** [comment]
Another option would be to add a `--swap-amount` option which would allow the user to specify the amount of XMR they want to buy and then display them with the amount of BTC they need to deposit to cover the fees and get the desired amount of XMR.

**Comment by thomaseizinger** [comment]
> Another option would be to add a `--swap-amount` option which would allow the user to specify the amount of XMR they want to buy and then display them with the amount of BTC they need to deposit to cover the fees and get the desired amount of XMR.

We had that at some point. It creates other usability issues: We cannot control how much money the user ends up sending to the address. Even if they launch the tool with `--swap-amount 0.5`, we need to deal with the fact that the user may send more / less money. The only thing we could do with this parameter is make a calculation for the user.

As a rule of thumb, most things that can relatively easily be built on top of the CLI (by parsing the output) are out of scope. Doing a calculation based on the quote that is displayed can easily be built on top of the already existing output.

Like I said in the previous comment, the output could be better to account for fees. We don't have the capacity to do that ourselves but I am happy to review / guide a PR.

[This](https://github.com/comit-network/xmr-btc-swap/blob/6ec5e34f8043df36aa9e7065c846cb382875f8e0/swap/src/bin/swap.rs#L403-L479) is the function in question. It has quite extensive test coverage that even captures the output of what is displayed to the user.

I would start with writing a test that asserts the output you'd want to see.
To do fee estimation, you will need access to the bitcoin wallet which - for testability purposes - is not available in this function. However, same as for the other parameters, you can pass in a closure that allows you to call into the fee estimation of the wallet. In the test, you just supply a static fee rate then.

**Comment by binarybaron** [comment]
I'd say we fix this by showing the network fees next to the minimum and maximum amount. Otherwise, the end user will not be able to predict exactly what amount of Bitcoin to send to initiate a swap.
