### ISSUE TITLE
Use Typesafety with expiries

### ISSUE THREAD

**Issue by D4nte** [comit-network/xmr-btc-swap#57]
Currently, t1 and t2 are represented as `u32`. Instead we should introduce two newtypes:
- `BlockHeight`: The (absolute) block height of a transaction or the expiry in absolute block height
- `RelativeHeight`: The relative height to express an expiry (from the moment to which a transaction is mined).

And ensure that it is not possible to sum 2 `BlockHeight`s but only a `BlockHeight` and one (or two) `RelativeHeight`.

**Comment by thomaseizinger** [comment]
Is this still valid?

**Comment by D4nte** [comment]
Resolved with #190
