### ISSUE TITLE
Swap CLI tries to create already existent wallet

### ISSUE THREAD

**Issue by cimble-code** [comit-network/xmr-btc-swap#572]
```
.\swap.exe buy-xmr --seller-addr *** --seller-peer-id *** --receive-address ***--testnet
Error: Unable to create Monero wallet, please ensure that the monero-wallet-rpc is available

Caused by:
    0: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.
    1: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.
```

**Comment by da-kami** [comment]
First question: Did you copy your command in or type it out?

I noticed`--testnet` is set at the end of the command which should not be possible.
The `--testnet` parameter is a global parameter that is to be specified globally (i.e. before a subcommand such as `buy-xmr`).

Please provide the actual command that was used so I can reproduce this (or confirm that the command was actually as specified above).

**Comment by cimble-code** [comment]
`.\swap.exe buy-xmr --receive-address 59McWTPGc745SRWrSMoh8oTjoXoQq6sPUgKZ66dQWXuKFQ2q19h9gvhJNZcFTizcnT12r63NFgHiGd6gBCjabzmzHAMoyD6 --seller-addr /ip4/127.0.0.1/tcp/9939 --seller-peer-id 12D3KooWBahvnaP6iSGHjY7RPKCXnWr3uzAnjK2QqvQAmKgidqjy --testnet`

This is the exact command I ran and it works just fine. I'm unable to reproduce the issue right now for the swap-cli but it's definitely an issue for the ASB.

How to reproduce:
1. Start the monero-wallet-rpc
`./monero-wallet-rpc --stagenet --daemon-host stagenet.community.xmr.to:38081 --rpc-bind-port 38083 --disable-rpc-login --wallet-dir ./`
2. Start the ASB
`.\asb --testnet start`
3. Wait for monero wallet to be opened
4. Force close ASB using `Strg-C`
5. Start the ASB again
`.\asb --testnet start`

```
←[2m2021-06-25 02:24:24←[0m ←[32m INFO←[0m Initialized tracing level=debug
←[2m2021-06-25 02:24:24←[0m ←[32m INFO←[0m Using config file at path=C:\Users\user\AppData\Roaming\xmr-btc-swap\config\asb\testnet\config.toml
←[2m2021-06-25 02:24:24←[0m ←[32m INFO←[0m Database and Seed will be stored in db_folder=C:\Users\user\AppData\Roaming\xmr-btc-swap\data\asb\testnet
←[2m2021-06-25 02:24:24←[0m ←[34mDEBUG←[0m Opening database at C:\Users\user\AppData\Roaming\xmr-btc-swap\data\asb\testnet\database
←[2m2021-06-25 02:24:24←[0m ←[34mDEBUG←[0m Reading in seed from C:\Users\user\AppData\Roaming\xmr-btc-swap\data\asb\testnet\seed.pem
←[2m2021-06-25 02:24:24←[0m ←[34mDEBUG←[0m Opening Bitcoin wallet
←[2m2021-06-25 02:24:35←[0m ←[34mDEBUG←[0m Opening Monero wallet
Error: Unable to create Monero wallet, please ensure that the monero-wallet-rpc is available

Caused by:
    0: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.
    1: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.
```
I think you need to either preemptively call [close_wallet](https://monerodocs.org/interacting/monero-wallet-rpc-reference/#close_wallet) or check if the primary address of the currently opened wallet matches the one the ASB wants to open.

**Comment by binarybaron** [comment]
I was just able to reproduce this error again. I'm not sure what caused it, but I think I closed the swap-cli while it was starting the monero-wallet-rpc. I am unable to restart another swap (even with another asb). It always fails with the same error.

`./swap --json --testnet --debug buy-xmr --change-address tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx --receive-address 59McWTPGc745SRWrSMoh8oTjoXoQq6sPUgKZ66dQWXuKFQ2q19h9gvhJNZcFTizcnT12r63NFgHiGd6gBCjabzmzHAMoyD6 --seller /dns4/xmr-btc-asb.coblox.tech/tcp/9939/p2p/12D3KooWCdMKjesXMJz1SiZ7HgotrxuqhQJbP5sgBm2BwP1cqThi
`
```
{"timestamp":"2021-09-05 17:32:21","level":"DEBUG","fields":{"message":"Opening database at /home/developer/.local/share/xmr-btc-swap/cli/testnet/database"}}
{"timestamp":"2021-09-05 17:32:21","level":"DEBUG","fields":{"message":"Reading in seed from /home/developer/.local/share/xmr-btc-swap/cli/testnet/seed.pem"}}
{"timestamp":"2021-09-05 17:32:23","level":"DEBUG","fields":{"message":"Starting monero-wallet-rpc","port":"41381"}}
Error: Unable to create Monero wallet, please ensure that the monero-wallet-rpc is available

Caused by:
    0: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.
    1: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.

```

**Comment by binarybaron** [comment]
I found out why this happens. It is related to https://github.com/comit-network/xmr-btc-swap/issues/835. I think the monero-wallet-rpc is sometimes not terminated when the swap cli is forcibly stopped (e.g. by Ctrl-C). The cli then creates a second instance of monero-wallet-rpc and when one tries to create a new wallet, it fails because the other monero-wallet-rpc instance has already opened a wallet with that name.
