### ISSUE TITLE
Swapping main-net coins with test-net coins is allowed

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#596]
Do we really want to allow `monero::network` and `bitcoin::network` to be independently configurable. I can't think of any legitimate use case for this.

I think a single field is better. A single field allows use to have fewer  `rendezvous namespaces`

```rust
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct Config {
    pub bitcoin_lock_mempool_timeout: Duration,
    pub bitcoin_lock_confirmed_timeout: Duration,
    pub bitcoin_finality_confirmations: u32,
    pub bitcoin_avg_block_time: Duration,
    pub bitcoin_cancel_timelock: CancelTimelock,
    pub bitcoin_punish_timelock: PunishTimelock,
    pub bitcoin_network: bitcoin::Network,
    pub monero_avg_block_time: Duration,
    pub monero_finality_confirmations: u64,
    pub monero_network: monero::Network,
}
```

**Comment by rishflab** [comment]
Not sure if we condense the config like I want actually because we use Monero stagenet with bitcoin testate

**Comment by rishflab** [comment]
Not sure if we condense the config like I want actually because we use Monero stagenet with bitcoin testnet

**Comment by thomaseizinger** [comment]
I agree that the internal data structure might be too flexible. However, from what is configurable through the interface, the user can only choose mainnet or testnet but not a mix!
