### ISSUE TITLE
[Feature] Allow ASB operator to print Monero address after initial deposit

### ISSUE THREAD

**Issue by sethsimmons** [comit-network/xmr-btc-swap#647]
While the address to deposit funds to when running the ASB is printed each time at startup before initial deposit, once there are funds in the wallet of the ASB it no longer prints address for the Monero wallet.

There is currently no way to print the address manually besides loading up the keys/cache for the Monero wallet manually into `monero-wallet-cli` or querying `monero-wallet-rpc` via a command like:

```
curl http://127.0.0.1:18083/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_address","params":{"account_index":0,"address_index":[0]}}' -H 'Content-Type: application/json'
```

Would be great to have a simple `swap addresses` option or similar to print addresses as needed after initial deposit.

**Comment by thomaseizinger** [comment]
The code for only printing the address when the balance is zero is here: https://github.com/comit-network/xmr-btc-swap/blob/cdb2939746e941b335fa8c7bbdc0f43a83c13013/swap/src/bin/asb.rs#L110-L118

I would accept a PR that changes this logic to print it unconditionally if that would help.

Adding a new command seems unnecessary to me. Users are encouraged to manage their funds by directly interacting with `monero-wallet-rpc`.

**Comment by sethsimmons** [comment]
Good call, probably unnecessary! Will close this but might open a PR later just for documenting the necessary RPC calls.
