### ISSUE TITLE
Do not WARN on list-sellers communication end

### ISSUE THREAD

**Issue by sethsimmons** [comit-network/xmr-btc-swap#660]
I've noticed that each time a buyer runs `list-sellers` against the rendezvous point, the ASB logs a WARN message like the below:

```
DEBUG New connection established peer=REDACTED address=/ip4/REDACTED/tcp/35740
 WARN Lost connection to peer: Connection error: I/O error: connection is closed peer=REDACTED address=/ip4/REDACTED/tcp/35740
 ```
 
Would be good to either not log this error when the communication is just the `list-sellers` ping or drop the log severity to DEBUG or similar.

**Comment by thomaseizinger** [comment]
Fair. We don't know the reason for why the user disconnected here but I guess we could generally downgrade that message to a `debug`. It is not something that the ASB provider can do about. Hence, lack of immediate action suggests that this is not actually a `warn`.

Would accept a PR that changes it to `debug`.

**Comment by sethsimmons** [comment]
> Fair. We don't know the reason for why the user disconnected here but I guess we could generally downgrade that message to a `debug`. It is not something that the ASB provider can do about. Hence, lack of immediate action suggests that this is not actually a `warn`.
> 
> Would accept a PR that changes it to `debug`.

Opened https://github.com/comit-network/xmr-btc-swap/pull/681.
