### ISSUE TITLE
ASB withdraws one output at a time instead of emptying wallet

### ISSUE THREAD

**Issue by sethsimmons** [comit-network/xmr-btc-swap#662]
When attempting to empty the ASB Bitcoin wallet via withdraw-BFF, the documented behavior is that if no amount is provided it will empty the wallet.

ATM the behavior is instead withdrawing one output at a time from the wallet.

**Comment by thomaseizinger** [comment]
That is certainly a bug although I don't quite know why that would happen.

**Comment by thomaseizinger** [comment]
[This](https://github.com/comit-network/xmr-btc-swap/blob/42125049413ea2d1fbf389ad9ff0642ea02d6aba/swap/src/bin/asb.rs#L216-L234) is where the withdraw is initiated. To investigate, I would recommend starting with adding a test [here](https://github.com/comit-network/xmr-btc-swap/blob/master/swap/src/bitcoin/wallet.rs#L894) where we initialize the test wallet with > 1 UTXO.

**Comment by rishflab** [comment]
resolved in PR
