### ISSUE TITLE
Cannot specify amount to withdraw from ASB wallet

### ISSUE THREAD

**Issue by sethsimmons** [comit-network/xmr-btc-swap#667]
When attempting to specify an amount to withdraw from the ASB wallet, there appears to be no way to actually provide the amount in a format that the tool will accept.

I have tried --amount:

- 0.01
- 0.01BTC
- 0.01 BTC
- 1000000
- "0.01"

Hopefully this is just me misunderstanding what the tool wants, but may also be a bug.

**Comment by thomaseizinger** [comment]
To clarify, the correct way of specifying the argument is a quoted string with denomination:

```
--amount '0.1 BTC'
```
