### ISSUE TITLE
monero wallet-rpc: download macos binaries over TLS

### ISSUE THREAD

**Issue by cirocosta** [comit-network/xmr-btc-swap#672]
Hi!

for the `macos` target, it seems like the `monero` binaries are being downloaded straight from `http`:

https://github.com/comit-network/xmr-btc-swap/blob/42125049413ea2d1fbf389ad9ff0642ea02d6aba/swap/src/monero/wallet_rpc.rs#L20-L21

I'm not familiar enough with `reqwest` to know if it'd force https under the hood (I guess not?), so I'd suggest that we rewrite that schema to `https` (from a `git blame`, couldn't tell if there was a reason for it or not, seems unintentional).

Thanks, and kudos on the work, excited to see traction coming up :)

**Comment by thomaseizinger** [comment]
Agreed, would definitely accept a PR for this.

Don't actually need an automated test for this, some manual testing will be sufficient.

**Comment by ikmckenz** [comment]
I think this can be closed, was resolved in: https://github.com/comit-network/xmr-btc-swap/commit/6e7e39eea4f1149cd6490a0204c6545a86c3c14f#diff-01af5c1b76f72d3daae278d6472f554cb948af0ec3d7f8938e3b2127bc33f693R21

cc: @delta1
