### ISSUE TITLE
Swap failed, failed to broadcast Bitcoin cancel transaction

### ISSUE THREAD

**Issue by TA1002** [comit-network/xmr-btc-swap#674]
Rather than try to explain the issue, I decided to just copy/paste my terminal:

user@host:~/swaptool$ ./swap history
+--------------------------------------+----------------------------+
| SWAP ID                              | STATE                      |
+===================================================================+
| 7e9c4b62-1411-46be-b06e-77511f06969b | Cancel timelock is expired |
+--------------------------------------+----------------------------+
user@host:~/swaptool$ ./swap resume --swap-id 7e9c4b62-1411-46be-b06e-77511f06969b
Connected to Alice at /ip4/51.15.44.142/tcp/9939/p2p/12D3KooWAPci3x4GuWDi9P86efnR1q9a7phKnPwnwQcRNMW2HDUy
Error: Failed to broadcast Bitcoin cancel transaction 0a03a88c6eaf61defc83943b874ecec5bba0884338fb0774f97808bd78f86117

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))

**Comment by thomaseizinger** [comment]
Can you manually refund the swap?

**Comment by TA1002** [comment]
How would I accomplish this?

I guess I should explain more in case there's a misunderstanding. I was trying to execute a swap. I had already sent the BTC to the provided address. While I was at the stage "Waiting for Alice to lock Monero", I lost connection. Eventually I figured out how to check the history of the swap and was able to "resume" with the correct swap ID. Again I was at the stage "Waiting for Alice to lock Monero". After several minutes, I received a message indicating this had timed out and that the swap failed. 

I interpreted the messages above in my original post that the BTC would be returned to my refund address, but that had also failed. Is that correct? 

Sorry if there's any misunderstanding on my part.

**Comment by TA1002** [comment]
Update: I noticed the "state" changed from "cancel timelock is expired" to "Bitcoin refundable"

So I attempted to use the refund command. But I still received an error:

user@host:~/swaptool$ ./swap history
+--------------------------------------+--------------------+
| SWAP ID                              | STATE              |
+===========================================================+
| 7e9c4b62-1411-46be-b06e-77511f06969b | Bitcoin refundable |
+--------------------------------------+--------------------+
user@host:~/swaptool$ ./swap refund --swap-id 7e9c4b62-1411-46be-b06e-77511f06969b
Error: Failed to broadcast Bitcoin refund transaction f22be86559579b6520dcc10b5de98b087cb75ae2a28116be0b9b452ac6f60411

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-25,\"message\":\"bad-txns-inputs-missingorspent\"}")))

**Comment by aypro** [comment]
how long did it take for the status to change to "Bitcoin refundable" ?

**Comment by TA1002** [comment]
> how long did it take for the status to change to "Bitcoin refundable" ?

I'm not sure. I did a "swap history" query shortly before I posted. At least 12 hours.

**Comment by thomaseizinger** [comment]
I seems that the cancel transaction has been broadcasted: https://mempool.space/tx/0a03a88c6eaf61defc83943b874ecec5bba0884338fb0774f97808bd78f86117

It has also been spent again already. Did you receive the BTC back in your wallet that you used to generate the refund address?

**Comment by TA1002** [comment]
> I seems that the cancel transaction has been broadcasted: https://mempool.space/tx/0a03a88c6eaf61defc83943b874ecec5bba0884338fb0774f97808bd78f86117
> 
> It has also been spent again already. Did you receive the BTC back in your wallet that you used to generate the refund address?

I have not. I checked both BTC wallets, just in case I mixed them up somehow.

I'm not very knowledgeable on how to navigate the blockchain, but I see no reference to my refund address in the link you provided. 

Also, if the BTC had been refunded, is there a reason the current "state" which still show "Bitcoin refundable"? Rather than something like "Bitcoin refunded"?

**Comment by thomaseizinger** [comment]
> I have not. I checked both BTC wallets, just in case I mixed them up somehow.

I am afraid that means that the ASB provider made use of the _punish_ spend path as a compensation for not being able to re-claim their locked up Monero which is only possible if the swap-tool issues the refund properly.

It is hard to say exactly what happened. For how long have you been offline after you've lost connection?

**Comment by aypro** [comment]
i think i'm at the same situation, history still says "cancel timelock is expired", and i can neither cancel nor refund the swap
`6bd9d919-58be-405b-a762-9e5d039a9247 | Cancel timelock is expired `
https://mempool.space/tx/9cea05feb6244f1e439fe380aaa3633ac2a9a4f94108ee171b97aa2f5ec59169

**Comment by aypro** [comment]
Now the state is "btc refundable" but i get this error, when i try `swap refund`

> Error: Failed to broadcast Bitcoin refund transaction 96185216c68e6ae8c7e56d41e308b1b3a336cec7cc870f635d5a24c8dec9e036
> 
> Caused by:
>     Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-25,\"message\":\"bad-txns-inputs-missingorspent\"}")))

**Comment by TA1002** [comment]
> > I have not. I checked both BTC wallets, just in case I mixed them up somehow.
> 
> I am afraid that means that the ASB provider made use of the _punish_ spend path as a compensation for not being able to re-claim their locked up Monero which is only possible if the swap-tool issues the refund properly.
> 
> It is hard to say exactly what happened. For how long have you been offline after you've lost connection?

Not long. I tried re-starting the swap several times, before I figured out how to use the "resume" command. It's hard to piece together exactly what the sequence of events was and the timeline since I didn't save the terminal logs.

I'm not sure if this matters, but I was trying to run the swap using Whonix, so my terminal was being routed through Tor. This probably didn't help in terms of connection stability. I've since run several swaps on my host OS with no issues.

**Comment by TA1002** [comment]
> Now the state is "btc refundable" but i get this error, when i try `swap refund`
> 
> > Error: Failed to broadcast Bitcoin refund transaction 96185216c68e6ae8c7e56d41e308b1b3a336cec7cc870f635d5a24c8dec9e036
> > Caused by:
> > Electrum(Protocol(String("sendrawtransaction RPC error: {"code":-25,"message":"bad-txns-inputs-missingorspent"}")))

My swap shows the same state and exact same error when attempting to refund.

**Comment by thomaseizinger** [comment]
> I'm not sure if this matters, but I was trying to run the swap using Whonix, so my terminal was being routed through Tor. This probably didn't help in terms of connection stability. I've since run several swaps on my host OS with no issues.

The swap protocol requires a stable connection to the other party, because we need to exchange crucial information to them. Without that, the swap cannot finish.

Please note that the swap tool has [native Tor support](https://github.com/comit-network/xmr-btc-swap/blob/master/docs/cli/README.md#tor) for communication to Alice. Connections to block explorers will still go through clearnet however.

If you don't have a stable connection and hence cannot exchange this information, Alice will eventually cancel the swap (by broadcasting the `cancel` transaction herself) and then later claim the BTC as a compensation for not being able to take the Monero back.

Note that, if you don't have a reliable connection to blockchain nodes, this may also happen because you _miss out_ on the Monero being locked.

> > Now the state is "btc refundable" but i get this error, when i try `swap refund`
> > > Error: Failed to broadcast Bitcoin refund transaction 96185216c68e6ae8c7e56d41e308b1b3a336cec7cc870f635d5a24c8dec9e036
> > > Caused by:
> > > Electrum(Protocol(String("sendrawtransaction RPC error: {"code":-25,"message":"bad-txns-inputs-missingorspent"}")))
> 
> My swap shows the same state and exact same error when attempting to refund.

The error message could be better here, yes.
This just means that the UTXO has already been spent, which is why you cannot refund.

As I explained above, this happens when the punish timelock expires after the swap was cancelled. To compensate Alice, she is allowed to take the locked up BTC.

If you haven't already, take a look at [this](https://comit.network/blog/2020/10/06/monero-bitcoin/) blog post to understand the protocol better.

I am going to close this ticket because nothing seems to be inherently wrong in how the tool behaves. I am also going to open to follow up issues to improve the error messages.
