### ISSUE TITLE
Does this support Rust 1.41.1 on arm32/armhf (the default RaspiOS package versions)?

### ISSUE THREAD

**Issue by xanoni** [comit-network/xmr-btc-swap#675]
```bash
$ rustc --version
rustc 1.41.1

$ cargo --version
cargo 1.42.1

$ cargo build
[...]
   Compiling bs58 v0.4.0
error[E0658]: `while` is not allowed in a `const fn`
   --> /home/xmr/.cargo/registry/src/github.com-1ecc6299db9ec823/bs58-0.4.0/src/alphabet.rs:107:9
    |
107 | /         while i < encode.len() {
108 | |             if base[i] >= 128 {
109 | |                 return Err(Error::NonAsciiCharacter { index: i });
110 | |             }
110 | |             }
...   |
120 | |             i += 1;
121 | |         }
    | |_________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/52000

error[E0658]: `if` is not allowed in a `const fn`
   --> /home/xmr/.cargo/registry/src/github.com-1ecc6299db9ec823/bs58-0.4.0/src/alphabet.rs:108:13
    |
108 | /             if base[i] >= 128 {
109 | |                 return Err(Error::NonAsciiCharacter { index: i });
110 | |             }
    | |_____________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49146

error[E0658]: `if` is not allowed in a `const fn`
   --> /home/xmr/.cargo/registry/src/github.com-1ecc6299db9ec823/bs58-0.4.0/src/alphabet.rs:111:13
    |
111 | /             if decode[base[i] as usize] != 0xFF {
112 | |                 return Err(Error::DuplicateCharacter {
113 | |                     character: base[i] as char,
114 | |                     first: decode[base[i] as usize] as usize,
115 | |                     second: i,
116 | |                 });
117 | |             }
    | |_____________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49146

error[E0658]: `match` is not allowed in a `const fn`
   --> /home/xmr/.cargo/registry/src/github.com-1ecc6299db9ec823/bs58-0.4.0/src/alphabet.rs:156:12
    |
156 |           [][match result {
    |  ____________^
157 | |             Ok(alphabet) => return alphabet,
158 | |             Err(_) => 0,
159 | |         }]
    | |_________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49146

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bs58`.
warning: build failed, waiting for other jobs to finish...
error: build failed
[...]
```

**Comment by thomaseizinger** [comment]
We are building against Rust 1.53: https://github.com/comit-network/xmr-btc-swap/blob/42125049413ea2d1fbf389ad9ff0642ea02d6aba/rust-toolchain.toml#L2
Generally, we always track the latest stable release of Rust for the applications that we are building.

We do attach binaries to our releases that are built using GitHub actions: https://github.com/comit-network/xmr-btc-swap/releases/tag/0.8.1

I am not sure if the provided armv7 binary runs on arm32 though but you are welcome to add a configuration to CI to build on more exotic targets.

If you need to build from source, you will need to acquire a recent Rust compiler from somewhere.

**Comment by thomaseizinger** [comment]
To answer this specific question: No we don't support building on Rust 1.41.1. Also, unless absolutely trivial, there will be no effort in trying to lower the MSRV, hence I am closing this issue as resolved.

I am open to additions to the CI process (checksums, signatures, etc) that make it more acceptable to download the pre-built binaries attached to the releases. Input welcome.

**Comment by xanoni** [comment]
Not suggesting that anyone should put in the effort to support an older Rust version ... was just curious if I screwed up. Thank you.

**Comment by thomaseizinger** [comment]
Sorry if my answer came across a bit harsh then :)
MSRV is a sensible topic in the space 😅

**Comment by xanoni** [comment]
> MSRV is a sensible topic in the space 😅

Hehe, had a similar problem before with `electrs` and there was a magic workaround ... so though that maybe something similar existed here: https://github.com/romanz/electrs/issues/207#issuecomment-881410192

But no worries, time to try `rustup` then.
