### ISSUE TITLE
Error: Failed to complete swap

### ISSUE THREAD

**Issue by Honzo1** [comit-network/xmr-btc-swap#676]
Hello, I sent 0.005 BTC, TXID: e5c7a0f3c1a8e4899222ccd7e6874187d68dbe5a890cf6b0d050b99f002cb874
--
Waiting for Bitcoin deposit deposit_address=bc1qe20tusnsdy77s3m0aedh3p9amy046pruxvskq9 max_giveable=0.00000000 BTC minimum_amount=0.00010000 BTC maximum_amount=0.01500000 BTC
Received Bitcoin new_balance=0.00050000 BTC max_giveable=0.00048162 BTC
Starting new swap amount=0.00048162 BTC fees=0.00001838 BTC swap_id=80e006d7-13db-4314-8165-157e609ab738
Relative bound of transaction fees reached. Falling back to: 1444.86 sats
Relative bound of transaction fees reached. Falling back to: 1444.86 sats
Error: Failed to complete swap

Caused by:
    InsufficientFunds { needed: 48961, available: 48960 }
--
I have not received XMR and BTC refund either. Can you advise what happened ?

Thank You.

**Comment by atadng2338** [comment]
I ran into this when using version 0.8.0 - check to see that you are using 0.8.1. Once downloading 0.8.1, you can use retry the swap - for me, it used the funds I already deposited.

**Comment by Honzo1** [comment]
where should I download 0.8.1. ?

**Comment by thomaseizinger** [comment]
Checkout the releases page: https://github.com/comit-network/xmr-btc-swap/releases

**Comment by thomaseizinger** [comment]
Version 0.8.1 should fix this, let me know if it doesn't.

**Comment by Honzo1** [comment]
dear Thomas, thank you for an answer. Unfortunately, I use Mac and there is not MAC version. Also I would like to ask you, what would be with BTC what I have transferred ? I have not received any refund. Is it lost ? If swap wasn't happened It supposed to be returned - TX fee.

**Comment by thomaseizinger** [comment]
The MAC version is the one with "Darwin" in the name. That is the name of the foundational UNIX components that underly MacOS.

Your funds are not lost, they sit in the internal wallet of the tool and will be available for the next swap.
