### ISSUE TITLE
ASB cli  (Lost connection to peer: Handler error)

### ISSUE THREAD

**Issue by dvd280** [comit-network/xmr-btc-swap#680]
I am on win10, and I am trying to get an ASB running with a rendezvous connection. (on mainnet).
After my asb launches, it tries to connect to a rendezvous node, it manages to connect - but seems to disconnect after a few seconds. 
My logs:

` 
>New connection established peer=12D3KooWQUt9DkNZxEn2R5ymJzWj15MpG6mTW84kyd8vDaRZi46o address=/dnsaddr/rendezvous.coblox.tech/p2p/12D3KooWQUt9DkNZxEn2R5ymJzWj15MpG6mTW84kyd8vDaRZi46o

>Successfully registered with rendezvous node

>Lost connection to peer: Connection error: Handler error: Connection closed due to expired keep-alive timeout. peer=12D3KooWQUt9DkNZxEn2R5ymJzWj15MpG6mTW84kyd8vDaRZi46o address=/dnsaddr/rendezvous.coblox.tech/p2p/12D3KooWQUt9DkNZxEn2R5ymJzWj15MpG6mTW84kyd8vDaRZi46o`

I assume it has something to do with libp2p, but can't quiet nail it down.

**Comment by thomaseizinger** [comment]
This shouldn't be an issue. There is no need to keep the connection to the rendezvous node alive. Once the registration is about to expire a new connection will be established.

Did you experience an issue or are you just concerned about the logs?

**Comment by dvd280** [comment]
> This shouldn't be an issue. There is no need to keep the connection to the rendezvous node alive. Once the registration is about to expire a new connection will be established.
> 
> Did you experience an issue or are you just concerned about the logs?

I was concerned about the logs, as the docs arent very clear on how the the rendezvous node knows whether my asb is still live ( if the registry requires a temporary connection, is it possible that non active addresses are displayed by the node to swap users?

**Comment by thomaseizinger** [comment]
> > This shouldn't be an issue. There is no need to keep the connection to the rendezvous node alive. Once the registration is about to expire a new connection will be established.
> > Did you experience an issue or are you just concerned about the logs?
> 
> I was concerned about what the logs imply. The docs aren't very clear on how the rendezvous node knows whether my asb is still live. If the registry requires a temporary connection, is it possible that non active addresses are displayed by the node to swap users?
> (As an example - consider a case where an ASB registers with a rendezvous node, and then goes offline immediately after the connection is timed out)

Yes that is possible which is why registrations time out automatically if they are not renewed. Default lease time is 2h, maximum is 72h.

**Comment by thomaseizinger** [comment]
I think this is resolved but I do agree that docs could be improved here! :)
