### ISSUE TITLE
Error when trying to resume swap

### ISSUE THREAD

**Issue by TA1002** [comit-network/xmr-btc-swap#684]
After another failed connection (although by every other indication my internet was fine):

Lost connection to Alice at /ip4/51.15.44.142/tcp/9939/p2p/12D3KooWAPci3x4GuWDi9P86efnR1q9a7phKnPwnwQcRNMW2HDUy, cause: Connection error: Handler error: Ping timeout

Upon trying to resume the swap I get:

Error: Unable to create Monero wallet, please ensure that the monero-wallet-rpc is available

Caused by:
    0: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.
    1: JSON-RPC request failed with code -21: Cannot create wallet. Already exists.

Eventually, after attempting to restart the swap numerous times, eventually it reconnects:

johndoe@User-Computer:~/swaptool$ ./swap resume --swap-id 7d5da16b-8967-4a80-8184-daffa06aed24
Connected to Alice at /ip4/51.15.44.142/tcp/9939/p2p/12D3KooWAPci3x4GuWDi9P86efnR1q9a7phKnPwnwQcRNMW2HDUy
Waiting for Alice to lock Monero

However I've been stuck at "Waiting for Alice to lock Monero" for at least an hour (The BTC I sent has seen 18 confirmations). Something tells me that Alice already locked the Monero, and I missed it. If this is the case, is there any chance of getting the BTC refunded?

**UPDATE**

The swap did indeed fail:

johndoe@User-Computer:~/swaptool$ ./swap resume --swap-id 7d5da16b-8967-4a80-8184-daffa06aed24
Connected to Alice at /ip4/51.15.44.142/tcp/9939/p2p/12D3KooWAPci3x4GuWDi9P86efnR1q9a7phKnPwnwQcRNMW2HDUy
Waiting for Alice to lock Monero
Failed to get status of script: Failed to subscribe to header notifications: Made one or multiple attempts, all errored:
	- CloseNotify alert received
 txid=9114239d586a8a83bc62c7d7a289dcef601a1dc1d534db4c20f06feaedc6931a
Alice took too long to lock Monero, cancelling the swap
Error: Failed to broadcast Bitcoin cancel transaction 51b125cf7f0bcab77c42e2fa919f499fcca37dfa7b7ff5e8330b9cfa6834a397

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))

**Comment by thomaseizinger** [comment]
> Something tells me that Alice already locked the Monero, and I missed it. If this is the case, is there any chance of getting the BTC refunded?

Yes. The cancel timelock is 72 blocks, that is about 12 hours. After that, you should be able to refund your coins. If another 12 hours pass after that, Alice can publish the punish transaction.

To resolve the ping timeout, can you try the `preview` build that is currently available?

**Comment by TA1002** [comment]
> > Something tells me that Alice already locked the Monero, and I missed it. If this is the case, is there any chance of getting the BTC refunded?
> 
> Yes. The cancel timelock is 72 blocks, that is about 12 hours. After that, you should be able to refund your coins. If another 12 hours pass after that, Alice can publish the punish transaction.
> 
> To resolve the ping timeout, can you try the `preview` build that is currently available?

Yes, I can try that. I updated my original post with the error I received after the swap failed. This is the exact same error I received in my previous issue I opened, but I failed to capture the original instance of it (I only captured it when I tried to "resume" my swap). What are the consequences of "Failed to broadcast Bitcoin cancel transaction"?

**Comment by TA1002** [comment]
It's been at least 12 hours, so I tried the following:

johndoe@User-Computer:~/swaptool$ ./swap refund --swap-id 7d5da16b-8967-4a80-8184-daffa06aed24
Error: Cannot refund because swap 7d5da16b-8967-4a80-8184-daffa06aed24 was not cancelled yet. Make sure to cancel the swap before trying to refund.
johndoe@User-Computer:~/swaptool$ ./swap cancel --swap-id 7d5da16b-8967-4a80-8184-daffa06aed24
Manually cancelling swap swap_id=7d5da16b-8967-4a80-8184-daffa06aed24
The cancel transaction cannot be published yet, because the timelock has not expired. Please try again later

swap history still shows "Cancel timelock is expired"

**Comment by kirtspaulding** [comment]
Had the same issue, posted in another bug report

**Comment by rishflab** [comment]
User was able to recover funds and the bug was address in #724
