### ISSUE TITLE
Why is a stagenet monero address expected from me when I run swap with --testnet?

### ISSUE THREAD

**Issue by jerzybrzoska** [comit-network/xmr-btc-swap#698]
I ran:
```
swap --testnet buy-xmr  --change-address tb1qf9p5mrl2mf4ulae257ewj2rns6hsu2y4p8j0q2 --receive-address 9saDH6XysCu26zQiHNf5BCE83F5TwdBm8GLm6oftj4FqFsAAdh8NNRFT7zcQD4Xx6EFK763hKuB4CSbyLKzMG9vAKZiM2eb --seller /dnsaddr/unstoppableswap.net/p2p/12D3KooWLHbHtkK53WoBA82Yht3PCCx6KXYxoJ6QqgXg1rSNtWhR
```
I got the following output:

>Error: Invalid monero address provided, expected address on network Stagenet but address provided is on Testnet

The XMR address provided by me [is a testnet address][1]. Why is a stagenet monero address expected from me when I run swap with `--testnet`?

[1]: https://testnet.xmrchain.com/search?value=9saDH6XysCu26zQiHNf5BCE83F5TwdBm8GLm6oftj4FqFsAAdh8NNRFT7zcQD4Xx6EFK763hKuB4CSbyLKzMG9vAKZiM2eb

**Comment by rishflab** [comment]
The `--testnet` flag refers to bitcoin testnet.
If `--testnet` is used,  we swap testnet bitcoin with stagenet monero. 
If `--mainnet` is used, we swap mainnet bitcoin with mainnet monero.

This should be documented better. Feel free to open a PR to improve the docs.

**Comment by jerzybrzoska** [comment]
> If --mainnet is used, we swap mainnet bitcoin with mainnet monero.

`--mainnet` flag is not described in the output of `swap help`, only `--testnet` is mentioned. I assume that `--mainnet` is the default, is it? Can I just skip it when I want to transact on mainnet?

**Comment by rishflab** [comment]
merged
