### ISSUE TITLE
Deposited amount is less than `min_quantity`

### ISSUE THREAD

**Issue by fbion** [comit-network/xmr-btc-swap#699]
Received Bitcoin new_balance=0.00010000 BTC max_giveable=0.00009527 BTC
Deposited amount is less than `min_quantity`

How much should i transfer
What to do next?

**Comment by fbion** [comment]
Received Bitcoin new_balance=0.00030231 BTC max_giveable=0.00010031 BTC
Starting new swap amount=0.00010031 BTC fees=0.00020200 BTC swap_id=
Published Bitcoin transaction txid=
Waiting for Alice to lock Monero

**Comment by thomaseizinger** [comment]
Duplicate of https://github.com/comit-network/xmr-btc-swap/issues/559.

Also, judging from the 2nd comment, things seem to work after depositing more BTC.
