### ISSUE TITLE
Add command to print wallet seed phrases for internal wallet

### ISSUE THREAD

**Issue by mygiterino** [comit-network/xmr-btc-swap#700]
Would like an integrated command/method or separate tool to display wallet seed phrases from internal ASB XMR & BTC wallets. 

Should be plausible to generate from seed.pem string or similar hash function.

**Comment by thomaseizinger** [comment]
There is no internal XMR wallet, we are utilizing `monero-wallet-rpc` for that.

For BTC it makes sense to print the seed phrase / extended private key. Probably best in form of the descriptor that is being used to things are unambiguous.
