### ISSUE TITLE
Incomplete transaction, how do i recover BTC

### ISSUE THREAD

**Issue by dzovani** [comit-network/xmr-btc-swap#701]
i initialized swap, sent BTC , than my client cannot connect to counterparty, how do i resume or cancel swap and return BTC

 ./swap history
+---------+-------+
| SWAP ID | STATE |
+=================+
+---------+-------+

history is empty

Lost connection to Alice at /dnsaddr/conspiracy.commitcri.me/p2p/12D3KooWQ7VgSvCD5DXKBYGJx6dK4pmx9B7LGr3amshvLwccuAHo, cause: Connection error: I/O error: connection is closed
Failed to dial Alice: Pending connection: Transport error: select error: Protocol error: I/O error: Connection refused (os error 111) 

thanx

**Comment by rishflab** [comment]
you can get a list of swaps with
`.swap history`

and then you can force cancel the swap with 

`./swap cancel --force --swap-id [SWAP ID]`

**Comment by dzovani** [comment]
its empty


./swap history
+---------+-------+
| SWAP ID | STATE |
+=================+
+---------+-------+

**Comment by fbion** [comment]
./swap --debug balance

**Comment by dzovani** [comment]
./swap --debug balance
Error: error: Found argument 'balance' which wasn't expected, or isn't valid in this context

USAGE:
    swap --debug

For more information try --help

**Comment by fbion** [comment]
> ./swap --debug balance
> Error: error: Found argument 'balance' which wasn't expected, or isn't valid in this context
> 
> USAGE:
> swap --debug
> 
> For more information try --help

try ver 0.8.2
https://github.com/comit-network/xmr-btc-swap/releases/tag/0.8.2

**Comment by dzovani** [comment]
./swap balance
Bitcoin balance is 0.00060000 BTC

./swap history
+---------+-------+
| SWAP ID | STATE |
+=================+
+---------+-------+

**Comment by rishflab** [comment]
User was able to recover funds and the bug was address in #724 and #705
