### ISSUE TITLE
Swap id not found in database

### ISSUE THREAD

**Issue by paperkut1** [comit-network/xmr-btc-swap#710]
Swap failed after depositing bitcoin due to seller's xmr balance too low to fulfill. The amount sent was less than max shown. Now swap history shows nothing and can't cancel due to error of id not found in database. Deposit has more than 72 confirmations.

Any help is greatly appreciated. 
Thanks

**Comment by rishflab** [comment]
Thanks for the bug report. This a somewhat known issue. 

Your deposited funds are in the `swap-cli` wallet. We are adding a feature to check the `swap-cli` balance and allow the user to withdraw funds in this wallet (#704). Once this PR is merged you should be able to retrieve your funds.

**Comment by nanostos** [comment]
> Thanks for the bug report. This a somewhat known issue.
> 
> Your deposited funds are in the `swap-cli` wallet. We are adding a feature to check the `swap-cli` balance and allow the user to withdraw funds in this wallet (#704). Once this PR is merged you should be able to retrieve your funds.

Is Alice able to execute the punish command in this state? I.e. has the bitcoin pre-sign been published?

**Comment by rishflab** [comment]
> > Thanks for the bug report. This a somewhat known issue.
> > Your deposited funds are in the `swap-cli` wallet. We are adding a feature to check the `swap-cli` balance and allow the user to withdraw funds in this wallet (#704). Once this PR is merged you should be able to retrieve your funds.
> 
> Is Alice able to execute the punish command in this state? I.e. has the bitcoin pre-sign been published?

I am assuming paperkut1 swap-cli has not published bitcoin TxLock in this case based off his report that swap history shows nothing. My assumption would be incorrect if there is a bug where bitcoin TxLock is published but the swap is not saved in history (this would be the first reported instance of that happening). Debug logs would help me confirm this.

If the bitcoin TxLock has been published then Alice can punish after 72 blocks.

**Comment by paperkut1** [comment]
I was able to access the wallet with the update. Transferred funds with command withdraw-btc --address 

Thanks
