### ISSUE TITLE
Cahoot (CoinJoin) semi decentralised providing 

### ISSUE THREAD

**Issue by cryptoxico** [comit-network/xmr-btc-swap#720]
P2P Semi-Centralised cahoot providing.
The purpose of this protocol is providing Cahoots partners from different parties 

Example : 
Bob want to atomic-swap his bitcoins for Monero.
John want to buy something on JoinMarket

We can have a service installed on theses market/sites/ect they can communicate together with the bitcoin lightning network and organisating cahoots processus

**Comment by thomaseizinger** [comment]
I don't fully follow what exactly you are proposing but it seems to be more of a discussion rather than an actual issue, so I am going to move this to a discussion :)
