### ISSUE TITLE
Encrypted Signature Documentation 

### ISSUE THREAD

**Issue by AAH20** [comit-network/xmr-btc-swap#744]
https://github.com/comit-network/xmr-btc-swap/blob/e8007cc1cb20c599b587790b69b1361d95b8eca7/swap/src/network/encrypted_signature.rs

that needs an extensive demonstration , risk assessment declaration , which might lead to new wallet development approaches.

**Comment by rishflab** [comment]
The file you have linked is a very small and comparatively small part of the whole protocol. That code using the `RequestResponse` protocol from libp2p so Bob can send the encrypted sig to Alice.

Feel free to open a PR to show us what you mean.
