### ISSUE TITLE
unable to locate package

### ISSUE THREAD

**Issue by klaods** [comit-network/xmr-btc-swap#758]
currently using Ubuntu 20.04.3 LTS
tried downloading and installing asb with:

sudo apt install https://github.com/comit-network/xmr-btc-swap/releases/latest

results:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package https://github.com/comit-network/xmr-btc-swap/releases

**Comment by rishflab** [comment]
> currently using Ubuntu 20.04.3 LTS
> tried downloading and installing asb with:
> 
> sudo apt install https://github.com/comit-network/xmr-btc-swap/releases/latest
> 
> results:
> 
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package https://github.com/comit-network/xmr-btc-swap/releases

I dont use apt and am not familiar with the apt install command. Have you tried downloading the release and running the binary directly?

**Comment by klaods** [comment]
im fairly new to the linux world and have had no prior coding experience. how would i go about downloading the release and running the binary?

> > currently using Ubuntu 20.04.3 LTS
> > tried downloading and installing asb with:
> > sudo apt install https://github.com/comit-network/xmr-btc-swap/releases/latest
> > results:
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > E: Unable to locate package https://github.com/comit-network/xmr-btc-swap/releases
> 
> I dont use apt and am not familiar with the apt install command. Have you tried downloading the release and running the binary directly?

**Comment by rishflab** [comment]
> im fairly new to the linux world and have had no prior coding experience. how would i go about downloading the release and running the binary?
> 
> > > currently using Ubuntu 20.04.3 LTS
> > > tried downloading and installing asb with:
> > > sudo apt install https://github.com/comit-network/xmr-btc-swap/releases/latest
> > > results:
> > > Reading package lists... Done
> > > Building dependency tree
> > > Reading state information... Done
> > > E: Unable to locate package https://github.com/comit-network/xmr-btc-swap/releases
> > 
> > 
> > I dont use apt and am not familiar with the apt install command. Have you tried downloading the release and running the binary directly?

https://github.com/comit-network/xmr-btc-swap/releases/tag/0.8.3 if you look here, there are release binaries right provided. I don't mean to be rude but if you do not know how to download, extract and execute a binary from github, running an ASB might be too advanced for you. 

You don't need to be a coder to run the ASB but having knowledge of how to run/ manage and pass flags to command line application is definitely a pre-requisite. You can learn all these things on the internet.
