### ISSUE TITLE
Change log level of `Advancing state` from `trace` to `debug` for swap-cli

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#759]
I'm looking into potentially developing a GUI for the swap-cli. In order to display instructions and details about the current state of the swap to the user, I need to derive the internal swap state from the log output. Would it be possible to change the log level of `Advancing state` from `trace` to `debug`? (or is it somehow possible to also display logs with a log level of `trace`)

https://github.com/comit-network/xmr-btc-swap/blob/1f371ecfee0008fecec97886270dbd932507e213/swap/src/protocol/bob/swap.rs#L61

**Comment by rishflab** [comment]
Hmm  I will see if it can be done with a environment variable, otherwise I will change it to be debug or add a flag.

**Comment by binarybaron** [comment]
> I can change it debug level.
>
Thanks!. I tried setting the RUST_LOG env variable, but that doesn't seem to work.

Currently I plan to use logs with one of the following message attributes to derive the swap state (for the happy-path only). I have not yet looked into the other paths (refund, punish)
- Received quote
- Waiting for Bitcoin deposit
- Received Bitcoin
- Starting new swap (I think this was changed in the latest preview release)
- Published Bitcoin transaction
- Bitcoin transaction status changed
- Alice locked Monero
- Received new confirmation for Monero lock tx
- Successfully transferred XMR to wallet
