### ISSUE TITLE
`history` and `balance` command does not work with `--json` flag

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#766]
`./swap --testnet --json history` and `./swap --testnet --json balance` should output the swap history / balance in a JSON format instead of printing an ASCII table / text.

**Comment by rishflab** [comment]
Thanks for pointing this out.  Should be able to fix this.

Is this for the GUI you are working on?

**Comment by binarybaron** [comment]
> Thanks for pointing this out. Should be able to fix this.
> 
> Is this for the GUI you are working on?

Yes, it is. I haven't started working on the actual GUI yet, but I've been thinking about how best to process the logs, create child processes, which framework to use for the user interface, ...

**Comment by rishflab** [comment]
> > Thanks for pointing this out. Should be able to fix this.
> > Is this for the GUI you are working on?
> 
> Yes, it is. I haven't started working on the actual GUI yet, but I've been thinking about how best to process the logs, create child processes, which framework to use for the user interface, ...

We are going to switch to sqlite as the DB (#133). One of the reasons we are making this switch is that sqlite libraries are available for most languages/platforms making it easier to build other applications on top of xmr-btc-swap. That should allow you to get a swap history with a SQL query. Does that work for you?

**Comment by binarybaron** [comment]
That would certainly work and make it much easier to be able to access the data.

**Comment by binarybaron** [comment]
Same goes for the `balance` command.

**Comment by xmrswapme** [comment]
Hello-

I just wanted to remark that we have successfully created a GUI for the swap CLI interface that interprets JSON and non-JSON output. It has not been fully tested as of yet, as we conducted around 10-12 swaps, 4 of which were successful and the others which gave us errors that we were able to handle appropriately. 

In those swaps, we did not need to resume, cancel, or refund any of the swaps, so we don't know the JSON output for these commands. If anyone can provide us with more JSON output, it would benefit our mission in spreading the word of this wonderful implementation. 

The GUI is a local webserver ran by Flask. It provides a database of market makers to choose from that is collated via user submission through our website 

https://xmrswap.me 

You can find out more and take a look at the screenshots at our repo:

 https://github.com/xmrswapme/swapfe

It's very early testing and the more JSON output we get the more we can build around it.
