### ISSUE TITLE
UnstoppabelSwap.net generated command generates error

### ISSUE THREAD

**Issue by scootercommuter** [comit-network/xmr-btc-swap#768]
UnstoppableSwap.net provides the command:
mkdir -f ~/swaptool; cd ~/swaptool;If(!(test-path .\swap.exe) -or !((Get-FileHash .\swap.exe).Hash -eq "39a0e8f01d06647a9b24208202b1290305980d0dedeb0c2bbc560dc34b896835")) {  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls11, [Net.SecurityProtocolType]::Tls12, [Net.SecurityProtocolType]::Ssl3  [Net.ServicePointManager]::SecurityProtocol = "Tls, Tls11, Tls12, Ssl3"  Write-Host "Downloading the latest version of the swap tool...";  Invoke-WebRequest -Uri https://github.com/comit-network/xmr-btc-swap/releases/download/0.8.3/swap_0.8.3_Windows_x86_64.zip -OutFile ./swap.zip;  Expand-Archive ./swap.zip -DestinationPath ./ -Force;}clear; Write-Host "Starting swap. This can take some time...";./swap buy-xmr --receive-address 89ovX1mVm3LPVMSKhAEQfZfVJUfoougYniTDaKo146TGjCVKf8FZQrFgovXYut1pZbPdFDgFjJZavSwuHcKgZNP7LGCaGfg --seller /ip4/51.15.44.142/tcp/9939/p2p/12D3KooWAPci3x4GuWDi9P86efnR1q9a7phKnPwnwQcRNMW2HDUy --change-address bc1qrmttd295thc9xjdmlm6mn87er5mufg9lhvzuwl

Results in this error:
At line:1 char:359
+ ... tocolType]::Ssl3  [Net.ServicePointManager]::SecurityProtocol = "Tls, ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '[Net.ServicePointManager]::SecurityProtocol' in expression or statement.
At line:1 char:432
+ ... er]::SecurityProtocol = "Tls, Tls11, Tls12, Ssl3"  Write-Host "Downlo ...
+                                                        ~~~~~~~~~~
Unexpected token 'Write-Host' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by binarybaron** [comment]
Did you run the command with PowerShell? (Not cmd.exe)

**Comment by thomaseizinger** [comment]
unstoppableswap.net is an unrelated third-party service. We do not provide any support for this here.
