### ISSUE TITLE
Configurable Bitcoin transaction fees for tx-fees that need agreement

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#78]
Alice will send the Bob the TxFeeRate as part of the QuoteResponse message. Bob can agree or disagree with this quote (xmr/btc rate and tx fee rate).  The agreed upon TxFeeRate is used to calculate the tx fees for all of the bitcoin transactions.

**Comment by thomaseizinger** [comment]
@rishflab to reword with the new strategy.

**Comment by thomaseizinger** [comment]
I think this is solved now. cc @da-kami @bonomat lets try not to have too many duplicate tickets please.
