### ISSUE TITLE
Inbound Communication Errors

### ISSUE THREAD

**Issue by xmrswapme** [comit-network/xmr-btc-swap#790]
**Describe the bug**

After a swap failed and was later resumed the following day, I've been getting communications errors when I restart the ASB server. For reference, the final state of the swap that began producing these errors was BtcPunished. 

I do not get these errors on my onion3 configuration, just the regular clearnet. They began after the aforementioned swap concluded. They only appear slightly after the start of the asb command and do not reappear unless I restart ASB. 

There has been swaps since then that completed just fine. I'm not sure what to make of these errors or how to resolve them. 

**Lost/trapped Funds**
No

**Debug logs**

ERROR Communication error: /comit/xmr/btc/bid-quote/1.0.0 failed because of an inbound timeout peer=QmVMswfEaP763HjCytSLas75P2dr9eSA7dpus9BP4EXuT4
ERROR Communication error: /comit/xmr/btc/transfer_proof/1.0.0 failed because of an inbound timeout peer=QmVMswfEaP763HjCytSLas75P2dr9eSA7dpus9BP4EXuT4
ERROR Communication error: /comit/xmr/btc/encrypted_signature/1.0.0 failed because of an inbound timeout peer=QmVMswfEaP763HjCytSLas75P2dr9eSA7dpus9BP4EXuT4

**Platform (please complete the following information):**

- ASB 
- Software Version:  0.8.3
- Operating System: Ubuntu 20.04

**Comment by devbordecraft** [comment]
I think it is how https://unstoppableswap.net/ handle price and uptime realtime update, don't know why it produce this errors though. Have the same message on my ASB.

**Comment by binarybaron** [comment]
This is probably our backend making requests to your ASB. Our LibP2P node does not allow inbound traffic and the asb incorrectly assumes that we want to start a swap.
