### ISSUE TITLE
Lower default bitcoin_finality_confirmations

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#796]
I think we should consider lowering the default confirmations required for Alice to lock her XMR from 2 to 1. This will significantly reduce the total time it takes to complete a swap (10 minutes) and will not significantly decrease security.
Is there a requirement for 2 confirmations at the protocol level that I'm not aware of?

**Comment by devbordecraft** [comment]
Don't see any drawback, I made this pull (#800) request to reduce the number of block for bitcoin confirmation.

**Comment by rishflab** [comment]
I will check with the team, I think the 2 block requirement was introduced as a workaround for a bug.

**Comment by rishflab** [comment]
I checked with the team. The 2 block requirement on the `cli` only affects the refund tx. 

On the ASB, the bitcoin finality confirmations can be set to 1 using the config file. This will get you the swap reduction time you desire.

**Comment by binarybaron** [comment]
Done
