### ISSUE TITLE
Bad API: Swap ID should not be an argument for swap()/run_until()

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#80]
Currently the swap() and run_until() functions take the swap id as an argument. The problem with this is we can retrieve an in-progress swap from the db using a swap_id and start executing it with a swap_id that does not match the swap_id we used to retrieve it.

We should re-design this API and use the type system to prevent the caller from making mistakes like this.

**Comment by da-kami** [comment]
I think this is outdated and can be closed, @rishflab ?

**Comment by thomaseizinger** [comment]
Outdated.
