### ISSUE TITLE
`monero-wallet-rpc` failed to fetch transaction, may need to be restarted txid=#################

### ISSUE THREAD

**Issue by TheGabelKeith77** [comit-network/xmr-btc-swap#814]
Hey all,

This is my first time to do an atomic swap.

Here is the exact steps of what I've done and what kind of error I'm getting

 -   I used https://unstoppableswap.net/ from https://web.getmonero.org/community/merchants/
 -   I chose a swap-provider and he/she is operating on the mainnet, not testnet.
 -   I followed the steps on the screen until I got this error

Waiting for Alice to lock Monero 
Alice locked Monero txid=##################### 
Waiting for Monero transaction finality txid=############## target_confirmations=10 
monero-wallet-rpc failed to fetch transaction, may need to be restarted txid=############### 
monero-wallet-rpc failed to fetch transaction, may need to be restarted txid=############### 
monero-wallet-rpc failed to fetch transaction, may need to be restarted txid=###############

That last line is iterating and won't stop for now.

Note 1: I input my address for the swap from my GUI wallet, which is fully synced, from the (Receive) tab, underneath the QR code, it starts with 4 as this is my first time to interact with XMR.

Note 2: I ran this swap on a linux mint vm with no monero wallet installed on it, I've my monero wallet on another vm.

Up till now the XMR didn't show on my wallet and I don't know what to do.

Thank you.

**Comment by rishflab** [comment]
> Hey all,
> 
> This is my first time to do an atomic swap.
> 
> Here is the exact steps of what I've done and what kind of error I'm getting
> 
>     * I used https://unstoppableswap.net/ from https://web.getmonero.org/community/merchants/
> 
>     * I chose a swap-provider and he/she is operating on the mainnet, not testnet.
> 
>     * I followed the steps on the screen until I got this error
> 
> 
> Waiting for Alice to lock Monero Alice locked Monero txid=##################### Waiting for Monero transaction finality txid=############## target_confirmations=10 monero-wallet-rpc failed to fetch transaction, may need to be restarted txid=############### monero-wallet-rpc failed to fetch transaction, may need to be restarted txid=############### monero-wallet-rpc failed to fetch transaction, may need to be restarted txid=###############
> 
> That last line is iterating and won't stop for now.
> 
> Note 1: I input my address for the swap from my GUI wallet, which is fully synced, from the (Receive) tab, underneath the QR code, it starts with 4 as this is my first time to interact with XMR.
> 
> Note 2: I ran this swap on a linux mint vm with no monero wallet installed on it, I've my monero wallet on another vm.
> 
> Up till now the XMR didn't show on my wallet and I don't know what to do.
> 
> Thank you.

What version is this. Are you on the new release 0.9.0?

**Comment by TheGabelKeith77** [comment]
I don't know to be honest, I just followed along the tutorial the website have posted.

**Comment by TheGabelKeith77** [comment]
Any idea what could've gone wrong ?

**Comment by rishflab** [comment]
Thanks for the logs. You are on the old release 0.8.3 so this issue is not due to newly introduced changes. I am not sure what the issue is. Have you tried the new release 0.9.0?

**Comment by devbordecraft** [comment]
Try cancel with --force or -f flag and refund with the same --force or -f flag

**Comment by devbordecraft** [comment]
Like that : 
./swap cancel -f --swap-id YOUR-SWAP-ID
./swap refund -f --swap-id YOUR-SWAP-ID

**Comment by TheGabelKeith77** [comment]
IT WORKED!!

I can't thank you enough @devbordecraft , thank you so so so much !!!!

Also, thanks for everyone who tried to help.

Will leave the thread for 24 hours before closing for any welcomed replies.
