### ISSUE TITLE
`'GLIBC_2.29' not found` on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#816]
**Describe the bug**
I can't execute the latest release (both cli and asb) version (0.9.0) on a clean install of `Ubuntu 18.04.5 LTS`

**Logs**
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
```bash
$ uname -a
Linux cznjb4IcAD 4.15.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
$ ./swap 
./swap: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./swap)
./swap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./swap)
```
```
$ ./asb 
./asb: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./asb)
./asb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./asb)
```
**Lost/trapped Funds**
No

**Platform :**

- CLI and ASB
- Software Version: 0.9.0
- Operating System: Ubuntu 18.04.5 LTS

**Comment by binarybaron** [comment]
> The CLI and ASB are built on ubuntu 20.04. 18.04.5 LTS does not support GLIBC_2.29 installed. It supports up to 2.27. This should be resolved by updating to 20.04 LTS. 
> 
> There maybe a way to install GLIBC_2.29 on your 18.04 system but I think it may be extremely problematic and upgrading is easier. 

Do you think it would be possible to revert the change that caused this problem? It's less about me and more about other people who might still be using Ubuntu 18.04 or other Linux variants that don't support this new version of GLIBC_2.29. I was able to run 0.8.3 on Ubuntu 18.04 as far as I remember.

**Comment by binarybaron** [comment]
I looked into this and think it's because GitHub Actions recently migrated the `ubuntu-latest` runner from `18.04` to `20.04`. (https://github.com/actions/virtual-environments/issues/1816)

I believe this can be fixed by just changing the os in `https://github.com/comit-network/xmr-btc-swap/blob/master/.github/workflows/build-release-binaries.yml` from `ubuntu-latest` to `ubuntu-18.04`

**Comment by ikmckenz** [comment]
Ubuntu 18 LTS standard support [ended](https://ubuntu.com/about/release-cycle) over a year ago, I propose closing this issue.
