### ISSUE TITLE
Fix issues with running multiple e2e tests (from one file)

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#84]
As described here https://github.com/comit-network/xmr-btc-swap/pull/81#issuecomment-744388832 when adding multiple e2e tests with Alice and Bob to one test file we run into the problem, that dialing fails upon test startup. This is most likely related to listening on the same port. 

Resolve by adding more elaborate handling for listening port, see https://github.com/comit-network/xmr-btc-swap/pull/81#issuecomment-744708102

**Comment by rishflab** [comment]
This is due to reuse of the same Multiaddr by Alice afaik
