### ISSUE TITLE
XMR IS LOCKED - Funds stuck in multisig

### ISSUE THREAD

**Issue by Macifyy** [comit-network/xmr-btc-swap#844]
My first ever transaction went through flawless and I received the funds. But transactions 2, and 3 have me reconsidering using unstoppableswap until it is in a later stage of development.

The 2 swaps have the status "XMR is locked"

If I attempt to cancel: "Error: Failed to broadcast Bitcoin cancel transaction Caused by: Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))"

If I attempt to resume swap: "Error: no rows returned by a query that expected to return at least one row"

Now the BTC is no longer in my possession and the XMR is still in the multisig (also not in my possession)

I should also mention that the original swap worked at first. Alice connected sent the XMR and then it errored.

"Received new confirmation for Monero lock tx txid= seen_confirmations=2 needed_confirmations=10
Oct 26 14:18:37.017  INFO Received new confirmation for Monero lock tx txid= seen_confirmations=3 needed_confirmations=10
Oct 26 14:21:13.012  INFO Received new confirmation for Monero lock tx txid= seen_confirmations=4 needed_confirmations=10
Oct 26 14:23:24.057  WARN Failed to get status of script: Failed to subscribe to header notifications: Made one or multiple attempts, all errored:
	- CloseNotify alert received"

**Lost/trapped Funds**
Yes

- CLI
- Software Version: This originally occurred on 0.8.3 but I have since updated to 0.9.0 and the funds are still stuck with my inability to cancel/refund
- Operating System: Windows

**Comment by ShinJii89** [comment]
I have the same.... in version 0.9.0 
Operating system: Linux

```
Nov 10 17:23:11.943  INFO Starting new swap swap_id=XXX
Nov 10 17:23:11.955 DEBUG Advancing state state=execution setup done
Nov 10 17:23:12.163  INFO Published Bitcoin transaction txid=XXXX kind=lock
Nov 10 17:23:12.169 DEBUG Advancing state state=btc is locked
Nov 10 17:23:12.746  INFO Waiting for Alice to lock Monero
Nov 10 17:23:16.957 DEBUG Found relevant Bitcoin transaction txid=XXXX status=unseen
Nov 10 17:24:20.035 DEBUG Bitcoin transaction status changed txid=XXXX new_status=in mempool old_status=unseen
Nov 10 17:26:23.441 DEBUG Got notification for new block block_height=709093
Nov 10 17:26:23.633 DEBUG Bitcoin transaction status changed txid=XXXX new_status=confirmed with 1 blocks old_status=in mempool
Nov 10 17:48:38.511  WARN Failed to get status of script: Failed to subscribe to header notifications: Made one or multiple attempts, all errored:
	- CloseNotify alert received
 txid=XXXX
```

When I try 
`./swap withdraw-btc --address XXXX`

There's an error:
`Error: OutputBelowDustLimit(0)`

**Comment by Macifyy** [comment]
This explains why the funds are locked but its meant for the CLI wallet (https://www.getmonero.org/resources/user-guides/howto_fix_stuck_funds.html)  I'm still unsure how to access my seed within unstoppable swap.

**Comment by ShinJii89** [comment]
I did `./swap resume --swap-id XXX` and it gave me back BTC.

**Comment by Macifyy** [comment]
REALLY? man I must be fucked being on windows. I also cant update my version from 0.8.3  to 0.9.0 or else Im unable to resume swap. I just get error messaged. i tried to resume swap and 

> "Connected to Alice at XXXX
> Lost connection to Alice at XXX, cause: Connection error: Handler error: upgrade apply error: EOF while parsing a value
> Communication error: /comit/xmr/btc/encrypted_signature/1.0.0 failed because the connection was closed we received a response peer=XXX"

**Comment by Macifyy** [comment]
Whenever I attempt to resume swap on the latest version 0.9.0 I receive this error

`Error: no rows returned by a query that expected to return at least one row`

**Comment by ShinJii89** [comment]
> Whenever I attempt to resume swap on the latest version 0.9.0 I receive this error
> 
> `Error: no rows returned by a query that expected to return at least one row`

I guess it f*cked up because you upgrade to 0.9.0 - there's something in changelog about database big changes...

**Comment by MrCyjaneK** [comment]
@Macifyy I have the same error as you:
```plain
cyjan@poppy /d/shm> ./swap resume --swap-id 87bf492d-ecda-40e8-a4b7-3c57f93fbfe4
Attempting to migrate old data to the new sqlite database...
Sucessfully migrated data to sqlite! Using sqlite.
Error: no rows returned by a query that expected to return at least one row
```
I'm on the very same binary - I've send funds in btc, but never got the xmr back

**Comment by gwumkt** [comment]
anyone was able to solve that?
﻿
<img width="1556" alt="Screenshot 2022-02-20 at 4 08 58 PM" src="https://user-images.githubusercontent.com/28900951/154846738-a3238b20-d375-4c42-85f6-810d0ccbb579.png">
