### ISSUE TITLE
Save logs for swap started with `--json` flag and save all logs in JSON format

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#849]
**Describe the bug**
The logs are not saved when the swap is started with the `--json` flag. This makes it much more difficult to reconstruct the previous swap state when resuming a swap, which is necessary for the GUI I am working on. In addition, it would be very helpful if all saved logs were saved in JSON format, as this would allow for the GUI to resume and display proper information about swaps that were not initiated using the GUI.

**Lost/trapped Funds**
No

**Platform (please complete the following information):**

- CLI
- Software Version All
- Operating System: All

**Comment by rishflab** [comment]
Hmm could you pipe the json output to a file? What about directly accessing the recently introduced sqlite database?

**Comment by binarybaron** [comment]
> Hi sorry for the delayed resposen.

No worries, I know you guys are also working on other projects.

> Could you pipe the json output to a file?

This is basically what we are doing at the moment, but it seems like something that should be handled by the cli itself. It would also help to be fully compatible with swaps initiated with the cli and not with our GUI, since we can't store logs manually for those and it would give us some important information about those swaps that can't be extracted from the database (or at least not easily)

https://github.com/UnstoppableSwap/unstoppableswap-gui/blob/d80b8082a1fb342e2b04cb26e5db22f634270a1e/src/main/cli/commands/buyXmrCommand.ts#L49-L60

> What about directly accessing the recently introduced sqlite database?

The GUI does use the sqlite database to retrieve information about the states of swaps but primarily for displaying information about swaps that have occurred in the past (swap history page). For running swaps we rely on the logs because some data is not easily extractable from the database (e.g transaction ids)
