### ISSUE TITLE
Bumping  BTC transaction fees 

### ISSUE THREAD

**Issue by orenchick** [comit-network/xmr-btc-swap#852]
**Describe the bug**
Hi.
I've made some  swaps that went through fluently.all good
The other day i was in a rush , the 0.002 btc confirmation process was a little too slow so , through Trezor Suite, i've Bumped the fees, unaware that bumping the fees will generate a new transaction that will not be recognized by the protocol.
so.
my bad obviously.
my only advice is to write down on the site  "**-do not bump fees, just wait, otherwise you will loose your fund**-" or something like that

thats it folks.
thanks for what you're doing.

**Lost/trapped Funds**
Yes 

**Platform (please complete the following information):**
windows 11

- CLI or ASB [eg. CLI]
- Software Version [e.g. 0.8.3]
- Operating System: [windows 11]

**Comment by binarybaron** [comment]
Closed with https://github.com/comit-network/xmr-btc-swap/commit/ebb7d24660a0dbe610208d46740d54c72ffaef9a
