### ISSUE TITLE
No unlocked balance after `btc is redeemed`

### ISSUE THREAD

**Issue by yokoloho** [comit-network/xmr-btc-swap#879]
**Describe the bug**
BTC -> XMR swap failed, can't receive (cancel don't work) BTC nor xmr.  
There was 10 confirmations of locking monero by Alice.

I had done swaps before but this time I got  error after 10 monero tx confirmations:
```
./swap resume --swap-id XXXXXXXXXXXXXX
Connected to Alice at /YYYYYYYYYYYYYYYYYYYYYYYY
Error: JSON-RPC request failed with code -4: No unlocked balance in the specified account

Caused by:
    JSON-RPC request failed with code -4: No unlocked balance in the specified account
```
after resuming for a second time I got:
```
Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists.: JSON-RPC request failed with code -1: Wallet already exists.
Falling back to trying to open the the wallet if it already exists wallet_file_name=<swap-id>
Connected to Alice at /YYYYYYYYYYYYYYYY
Error: JSON-RPC request failed with code -4: No unlocked balance in the specified account

Caused by:
    JSON-RPC request failed with code -4: No unlocked balance in the specified account
```
cancel command message:
```
Error: Cannot cancel swap <swap-id> because it is in state btc is redeemed which is not refundable.
```
From my swap log file:
```
Dec 18 16:23:57.129  INFO Received new confirmation for Monero lock tx txid=<tx> seen_confirmations=10 needed_confirmations=10
Dec 18 16:23:57.141 DEBUG Advancing state state=xmr is locked
Dec 18 16:23:57.141 DEBUG Constructed Bitcoin spending transaction fee=1000
Dec 18 16:23:57.328 DEBUG Advancing state state=encrypted signature is sent
Dec 18 16:23:57.328 DEBUG Constructed Bitcoin spending transaction fee=1000
Dec 18 16:24:02.334 DEBUG Found relevant Bitcoin transaction txid=<tx> status=unseen
Dec 18 16:24:12.696 DEBUG Bitcoin transaction status changed txid=<tx> new_status=in mempool old_status=unseen
Dec 18 16:24:15.579 DEBUG Advancing state state=btc is redeemed
Dec 18 16:25:47.009 DEBUG Using existing sqlite database.
Dec 18 16:25:47.011 DEBUG Reading in seed from /home/user/.local/share/xmr-btc-swap/cli/mainnet/seed.pem
Dec 18 16:25:49.610 DEBUG Starting monero-wallet-rpc port=38355
Dec 18 16:25:51.572 DEBUG Opened Monero wallet monero_wallet_name=swap-tool-blockchain-monitoring-wallet
Dec 18 16:25:51.574 DEBUG Network layer initialized peer_id=<peer-id>
Dec 18 16:25:51.574 DEBUG Advancing state state=btc is redeemed
Dec 18 16:25:51.640  WARN Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists.: JSON-RPC request failed with code -1: Wallet already exists.
Dec 18 16:25:51.640  INFO Falling back to trying to open the the wallet if it already exists wallet_file_name=<swap-id>
```

**Lost/trapped Funds**
Yes

**Debug logs**
Please post your debug logs. You find them in:
Linux: /home/<user>/.local/share/xmr-btc-swap/logs
OSX: /Users/<user>/Library/ApplicationSupport/xmr-btc-swap/logs

**Platform (please complete the following information):**

- CLI
- swap 0.9.0
- Operating System: Arch

When I open <swap-id>.keys wallets with GUI there are no XMR on them.  
I found this https://github.com/comit-network/xmr-btc-swap/issues/877 and tried it with all generated wallets - no success.  
Please hint me where my monero is at the moment. Thanks

**Comment by da-kami** [comment]
This problem might be related to this ticket: https://github.com/comit-network/xmr-btc-swap/issues/537
We thought that this issue was related to a specific `monero-wallet-rpc` version. I checked the code of `0.9.0` and it points against `monero-wallet-rpc` `v0.17.2.0`. Latest is `v0.17.3.0`.

In rare cases we saw problems of the `monero-wallet-rpc` not picking up funds even though the transaction is on chain and spends to the generated wallet. It is still unclear why exactly this happens.

I created https://github.com/comit-network/xmr-btc-swap/pull/880 that should enable manual recovery. Note: I have not tested this, but we had instances where users were able to recover funds using the `monero-wallet-cli`. 
Once you have address and the view and spend key I'd recommend using the latest `monero-wallet-cli` or `monero-wallet-rpc` to try spending the funds.

**Comment by yokoloho** [comment]
I was able to claim my funds using hints from last post in this issue: https://github.com/comit-network/xmr-btc-swap/issues/767
## solution
Note block number (height) from appropriate log file in ` ~/.local/share/xmr-btc-swap/cli/mainnet/logs` 
Go to `~/.local/share/xmr-btc-swap/cli/mainnet/monero/monero-data`  
Open wallet generated by swap tool `monero-wallet-cli --wallet-file <swap-id>` (default password is blank)  
note main addres (starting with `4`)
list keys with `viewkey` and `spendkey` command  
make new wallet for same addr with `monero-wallet-cli --generate-from-keys <new wallet file name>`  
set custom height, or paste `2519014` if you having this issue after 2021.12.20  

After synchronizing new wallet you should see your monero. Good luck!
