### ISSUE TITLE
Replace cross_curve_dleq dependency with sigma_fun

### ISSUE THREAD

**Issue by luckysori** [comit-network/xmr-btc-swap#90]
### Motivation

The implementation of the cross-curve DLEQ proof from `sigma_fun` (subcrate of `secp256kfun`) is 2.5 times faster, quite a bit smaller and more likely to be correct.

**Comment by thomaseizinger** [comment]
Doesn't immediately benefit the project's goals, can be revisited if it ever causes problems.
