### ISSUE TITLE
Where is asb log files?

### ISSUE THREAD

**Issue by 3s3s** [comit-network/xmr-btc-swap#921]
**Describe the bug**
I have started asb with the command " ./asb --testnet start", left all default options. It seems that application working but I have no log messages. I tried looking for the log file but couldn't find it anywhere. /var/log/asb - is empty. 
`bash: cd: /home/asb/.local/share/xmr-btc-swap/logs: No such file or directory`

**Lost/trapped Funds**
No

**Debug logs**
no logs

**Platform (please complete the following information):**

Ubuntu 20

**Comment by xmrswapme** [comment]
I believe you will only get a logfile if you run it as a systemd daemon. We run ours in the console and constantly monitor it for the reason on not producing log files. Piping tee doesn't seem to help either if you looking to also output to a logfile.

**Comment by delta1** [comment]
Fixed in the latest release
