### ISSUE TITLE
No results with `swap list-sellers --rendezvous-point /dnsaddr/discover.unstoppableswap.net/p2p/12D3KooWA6cnqJpVnreBVnoro8midDL9Lpzmg8oJPoAGi7YYaamE --tor-socks5-port 9050`

### ISSUE THREAD

**Issue by denationalized** [comit-network/xmr-btc-swap#926]
**Description**
I ran `./swap list-sellers --rendezvous-point /dnsaddr/discover.unstoppableswap.net/p2p/12D3KooWA6cnqJpVnreBVnoro8midDL9Lpzmg8oJPoAGi7YYaamE --tor-socks5-port 9050` I got no results, i.e.:
```
+-------+--------------+--------------+--------+---------+
| PRICE | MIN_QUANTITY | MAX_QUANTITY | STATUS | ADDRESS |
+========================================================+
+-------+--------------+--------------+--------+---------+
```
Customizing the TorSocks port in `/etc/tor/torrc` does not better anything.

**Lost/trapped Funds**
No

**Debug logs**
I have not found any logs in `~/.local/share/xmr-btc-swap`, `~/.local/share/xmr-btc-swap/cli/mainnet/seed.pem` being the only
file there.

**Platform (please complete the following information):**
- CLI
- Version `0.10.2`, a binary downloaded from the releases. The issue was not present earlier, i.e. in version `0.8.2`.
- Operating System:  Ubuntu

**Comment by binarybaron** [comment]
I don't think this is a bug. ASBs can only register at one rendezvous point at a time and there just isn't a mainnet ASB registered with this specific rendezvous point.
