### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#936]
Interested in atomic swaps? Love coding Rust?

This project is looking for an active maintainer. There is a ton of interesting code in here, ranging from peer-to-peer networking, state machines to next-level cryptography for non-custodial protocols.

Mentorship to ease the on-boarding will be provided but it would be good if you bring a good chunk of curiosity yourself.

If you are interested, ping us on this issue.

**Comment by SovereignAndrey** [comment]
Hi @thomaseizinger Would be interested in getting involved! :)

**Comment by thomaseizinger** [comment]
Hi @SovereignAndrey!

That is great! Let's connect on Matrix to work out the details: @thomaseizinger:matrix.org

**Comment by lescuer97** [comment]
Hi @thomaseizinger I could be interested in being a mantainer!,  I've already sent you a matrix message ;)

**Comment by LeoNero** [comment]
Hi @thomaseizinger . I want to work with Monero during the summer so this is something that interests me.

**Comment by delta1** [comment]
Hey @thomaseizinger i am a rust developer at tari-project/tari - very keen on helping out. I’ll ping you on matrix

**Comment by delta1** [comment]
Current maintainers are: 

@binarybaron 
@lescuer97 
@delta1 

If you are interested in helping please reach out to us in the Comit-Monero matrix channel 

https://matrix.to/#/%23comit-monero:matrix.org
