### ISSUE TITLE
Failing tests due to deleted XMR.to docker image

### ISSUE THREAD

**Issue by binarybaron** [comit-network/xmr-btc-swap#938]
**Describe the bug**
The docker image that is being used for the monero tests has been deleted.

https://github.com/comit-network/xmr-btc-swap/blob/5373f697ed9ad71a1b832a677288c332b9d1f9cc/monero-harness/src/image.rs#L28

https://hub.docker.com/search?q=xmrto%2Fmonero%3Av0.17.2.0&type=image

I thought that this could be fixed by replacing this with [melotools/monero](https://hub.docker.com/r/melotools/monero) but the tests are still [failing](https://github.com/binarybaron/xmr-btc-swap/runs/5100453270?check_suite_focus=true)

**Lost/trapped Funds**
Yes or No

**Debug logs**
Please post your debug logs. You find them in:
Linux: /home/<user>/.local/share/xmr-btc-swap/logs
OSX: /Users/<user>/Library/ApplicationSupport/xmr-btc-swap/logs

**Platform (please complete the following information):**

- CLI or ASB [eg. CLI]
- Software Version [e.g. 0.8.3]
- Operating System: [e.g. Ubuntu]

**Comment by binarybaron** [comment]
https://github.com/comit-network/xmr-btc-swap/pull/942

**Comment by delta1** [comment]
#942 merged, thanks @binarybaron !

**Comment by delta1** [comment]
Weird they passed in #942 but I had the same failure locally, will take a look and potentially make a new issue.
