### ISSUE TITLE
ASB Balance Command broken?

### ISSUE THREAD

**Issue by xhwmerhfity** [comit-network/xmr-btc-swap#956]
When I try to check the balance using "asb balance" a prompt appears "Enter data directory for asb or hit return to use default" as if a new instance of the asb is being initiated.

This appears to be an error?

The asb instance is stopped at the time of trying to check the balance and otherwise runs correctly.

(This also happens when using "asb withdraw-btc" to withdraw bitcoin)

At the moment I am unable to use the ASB as I cannot access any BTC received.

**Comment by delta1** [comment]
> The asb instance is stopped at the time of trying to check the balance and otherwise runs correctly. 

What command are you using to run `asb` ? Is it testnet or mainnet?

Is it possible when you are calling `asb balance` you're running a different copy of the binary?

**Comment by xhwmerhfity** [comment]
Running on mainnet. 

Launched using: sudo systemctl start asb
Trying to check balance using: asb balance

Is this a syntax error on my part? 

I've used the guide at sethforprivacy.com 
Everything else works great (shows up on rendezvous, can start swaps etc.)

Thanks for replying.

**Comment by delta1** [comment]
Right so when you run as sudo you are running the binary as root. Without sudo you are running as your own current user. 

Try ‘sudo asb balance’

**Comment by xhwmerhfity** [comment]
Thanks. Yeah I've tried that with the same result.

Is there a way I can check the Bitcoin wallet has been created correctly (I don't see anything in the asb.log file saying that there's been a problem).

**Comment by delta1** [comment]
You may need to try read the systemd logs since you’re running it as a service. 

What does “asb config” give you? The same prompt? Where is it installed? You can try “which asb”

**Comment by delta1** [comment]
From Seth’s guide [1] it looks like systemd is running asb as the user “asb” so I think you’ll need to run the command as that user 

[1]: https://sethforprivacy.com/guides/run-an-atomic-swap-provider-advanced/

**Comment by xhwmerhfity** [comment]
Thanks for your help. Will reinstall and test on Monday - if it works I won't be so hasty posting issues in the future :)

**Comment by lescuer97** [comment]
@xhwmerhfity did you manage to getting it working withthe asb user?
