### ISSUE TITLE
Account for the locking fee for the quoting for sale 

### ISSUE THREAD

**Issue by lescuer97** [comit-network/xmr-btc-swap#962]
As mentioned by @binarybaron in this [PR](https://github.com/comit-network/xmr-btc-swap/pull/953#discussion_r813599982) The Monero locking fee should be subtracted from the max amount to trade.

**Comment by binarybaron** [comment]
I don't think we need another PR for this. Afaik this is already done for when the actual swap is started. You just need to subtract the fee from the Monero balance when calculating the `max_quantity`

**Comment by lescuer97** [comment]
you where right about this. I Added the fix [here](https://github.com/comit-network/xmr-btc-swap/pull/953/commits/ce54af8418747681fb815bbfe74255c154b1b731)

**Comment by lescuer97** [comment]
you where right about this. I added the fix [here ](https://github.com/comit-network/xmr-btc-swap/pull/953/commits/ce54af8418747681fb815bbfe74255c154b1b731) ;)
