### ISSUE TITLE
How to Withdraw Monero from ASB Wallet?

### ISSUE THREAD

**Issue by elibroftw** [comit-network/xmr-btc-swap#972]
**Describe the bug**

No easy way to withdraw XMR. I sent some XMR to test the ASB but given the two other issues I've faced, I won't be trying again for a while. 

**Lost/trapped Funds**
Yes

**Debug logs**
Please post your debug logs. You find them in:
Linux: /home/<user>/.local/share/xmr-btc-swap/logs
OSX: /Users/<user>/Library/ApplicationSupport/xmr-btc-swap/logs

**Platform (please complete the following information):**

- ASB v0.10.2
- Operating System: Windows 10

**Comment by lescuer97** [comment]
you can connect to the wallet from the [monero-wallet-cli](https://www.getmonero.org/resources/user-guides/monero-wallet-cli.html) and transfer the monero from there.

**Comment by elibroftw** [comment]
> you can connect to the wallet from the [monero-wallet-cli](https://www.getmonero.org/resources/user-guides/monero-wallet-cli.html) and transfer the monero from there.
> 

If it were that easy, I wouldn't be asking. I couldn't find any *.keys file.

**Comment by lescuer97** [comment]
have you check in the windows trash for it? If you don't have it would be really weird because they get created in the same place that abs-wallet

**Comment by elibroftw** [comment]
![image](https://user-images.githubusercontent.com/21298211/157106878-06201212-2963-4280-9705-014f32fd8dae.png)

**Comment by elibroftw** [comment]
There's also a seed.pem file, but I have no idea what it's for nor how I get its contents.

**Comment by elibroftw** [comment]
The docs should mention that the password is empty and that the wallet will be created in the same directory as the wallet that was opened and not in its own directory.

I'd rather prefer to be able to withdraw the funds from the CLI. As you can see I don't store the wallet files opened by RPC in the same directory as the wallet files since the GUI and the RPC cannot open the wallet file simultaneously.
